from __future__ import annotations

"""
stage_contractor_risk_probe.py

Purpose:
- Exercise the contractor_builder_v1 risk API surface in isolation
- Verify that the risk_register branch can:
  - create a real project
  - initialize workflow
  - create a lawful linked change packet
  - create a lawful linked decision entry
  - create a lawful risk entry
  - review the risk entry
  - transition the risk entry status
  - append risk records to risk_register/risks.jsonl
  - emit risk receipts for create/review/transition

Usage examples:
    python -m AI_GO.tests.stage_contractor_risk_probe
    python AI_GO/tests/stage_contractor_risk_probe.py

Notes:
- This is a probe, not a mocked unit test.
- It mounts only the contractor_builder_v1 router into a local FastAPI app.
- It builds the minimum lawful context using a real project, real workflow phase,
  linked change packet, and linked decision entry.
"""

import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Dict, List

from fastapi import FastAPI
from fastapi.testclient import TestClient


def _build_isolated_app() -> FastAPI:
    """
    Build a tiny isolated FastAPI app that mounts only the contractor router.
    """
    try:
        from AI_GO.api.contractor_builder_api import router as contractor_builder_router
    except Exception as exc:
        raise RuntimeError(
            "Unable to import isolated contractor builder router: "
            f"{exc}"
        ) from exc

    app = FastAPI(title="contractor_builder_v1_risk_probe_app")
    app.include_router(contractor_builder_router)
    return app


def _now_compact() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")


def _build_project_create_payload() -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "project_name": f"Contractor Risk Probe {unique}",
        "project_type": "Kitchen Remodel",
        "client_name": "Risk Probe Client",
        "pm_name": "Risk Probe PM",
        "jurisdiction": {
            "jurisdiction_id": "scottsburg-in",
            "authority_name": "Scottsburg Building Department",
            "city": "Scottsburg",
            "county": "Scott",
            "state": "IN",
        },
        "baseline_refs": {
            "schedule_baseline_id": f"schedule-baseline-{unique}",
            "budget_baseline_id": f"budget-baseline-{unique}",
            "compliance_snapshot_id": f"compliance-snapshot-{unique}",
        },
        "project_description": "Probe-created project for contractor risk verification.",
        "client_contact": "risk-probe-client@example.com",
        "pm_contact": "risk-probe-pm@example.com",
        "site_address": "654 Risk Lane, Scottsburg, IN",
        "portfolio_id": "portfolio-risk-probe",
        "oracle_snapshot_id": "",
        "exposure_profile_id": "",
        "notes": "Generated by stage_contractor_risk_probe.py",
    }


def _build_phase_templates() -> List[Dict[str, Any]]:
    return [
        {
            "template_id": "template-risk-demolition",
            "project_type": "Kitchen Remodel",
            "phase_name": "Demolition",
            "expected_duration_days": 3,
            "dependencies": [],
            "role_expectations": {
                "crew": ["demo crew"],
                "management": ["pm oversight"],
            },
            "management_checkpoints": ["site protection verified"],
            "client_gate_requirement": {
                "required": False,
                "checklist": [],
            },
            "notes": "Initial demolition phase.",
        }
    ]


def _post_create_project(client: TestClient, payload: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post("/contractor-builder/projects/create", json=payload)

    if response.status_code != 200:
        raise AssertionError(
            "Project create failed during risk probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected project create status='created', got: {data}")

    return data


def _post_initialize_workflow(
    client: TestClient,
    project_id: str,
    phase_templates: List[Dict[str, Any]],
) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/workflow/initialize",
        json={
            "project_id": project_id,
            "phase_templates": phase_templates,
            "overwrite": False,
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Workflow initialize failed during risk probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "initialized":
        raise AssertionError(f"Expected workflow status='initialized', got: {data}")

    return data


def _build_change_packet_kwargs(
    *,
    project_id: str,
    phase_id: str,
    budget_baseline_id: str,
    schedule_baseline_id: str,
    compliance_snapshot_id: str,
) -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "change_packet_id": f"change-packet-{unique}",
        "project_id": project_id,
        "phase_id": phase_id,
        "title": "Risk probe linked change packet",
        "originator_name": "Risk Probe PM",
        "originator_role": "Project Manager",
        "originator_org": "AI_GO Probe",
        "workflow_phase_state_snapshot_id": f"workflow-phase-snapshot-{unique}",
        "compliance_snapshot_id": compliance_snapshot_id,
        "drawing_revision_id": f"drawing-rev-{unique}",
        "budget_baseline_id": budget_baseline_id,
        "schedule_baseline_id": schedule_baseline_id,
        "scope_delta_description": "Linked change packet for risk context.",
        "added_items": ["limited demolition resequence"],
        "removed_items": [],
        "scope_notes": "Used only to provide risk linkage context.",
        "phase_status": "not_started",
        "disruption_multiplier": 1.0,
        "factors_applied": ["risk_probe_context"],
    }


def _post_create_change_packet(client: TestClient, packet_kwargs: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/change/create",
        json={"packet_kwargs": packet_kwargs},
    )

    if response.status_code != 200:
        raise AssertionError(
            "Change packet create failed during risk probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected change create status='created', got: {data}")

    return data


def _build_decision_entry_kwargs(
    *,
    project_id: str,
    phase_id: str,
    linked_change_packet_id: str,
    compliance_snapshot_id: str,
    schedule_baseline_id: str,
    budget_baseline_id: str,
) -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "decision_id": f"decision-{unique}",
        "project_id": project_id,
        "title": "Approve temporary access workaround",
        "decision_type": "Risk_Acceptance",
        "phase_id": phase_id,
        "linked_change_packet_id": linked_change_packet_id,
        "compliance_snapshot_id": compliance_snapshot_id,
        "schedule_baseline_id": schedule_baseline_id,
        "budget_baseline_id": budget_baseline_id,
        "drawing_revision_id": f"drawing-rev-{unique}",
        "oracle_snapshot_id": "",
        "expected_schedule_delta_days": 0.5,
        "expected_cost_delta_amount": 150.0,
        "expected_margin_delta_percent": None,
        "expected_risk_level": "Moderate",
        "notes_on_assumptions": "Temporary access conditions assumed stable.",
        "may_reference_in_owner_reports": True,
        "owner_report_reference_label": "temporary_access_workaround",
        "notes_internal": "Probe decision entry for risk linkage.",
        "attachments_refs": [],
    }


def _post_create_decision_entry(client: TestClient, entry_kwargs: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/decision/create",
        json={"entry_kwargs": entry_kwargs},
    )

    if response.status_code != 200:
        raise AssertionError(
            "Decision create failed during risk probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected decision create status='created', got: {data}")

    return data


def _build_risk_entry_kwargs(
    *,
    project_id: str,
    linked_decision_id: str,
    linked_change_packet_id: str,
) -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "risk_id": f"risk-{unique}",
        "project_id": project_id,
        "category": "Access_Logistics",
        "description": "Neighbor access restriction may slow debris haul-out and material staging.",
        "probability": "Moderate",
        "impact_level": "Moderate",
        "mitigation_strategy": "Coordinate haul windows and pre-stage materials earlier in the day.",
        "mitigation_owner": "Project Manager",
        "review_frequency": "weekly",
        "linked_decision_ids": [linked_decision_id],
        "linked_change_packet_ids": [linked_change_packet_id],
        "notes": "Probe risk entry for risk_register verification.",
    }


def _post_create_risk_entry(client: TestClient, entry_kwargs: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/risk/create",
        json={"entry_kwargs": entry_kwargs},
    )

    if response.status_code != 200:
        raise AssertionError(
            "Risk create failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected risk create status='created', got: {data}")

    return data


def _post_review_risk_entry(client: TestClient, entry: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/risk/review",
        json={
            "entry": entry,
            "reviewer_name": "Risk Probe Reviewer",
            "reviewer_role": "Project Manager",
            "notes": "Weekly review completed during probe.",
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Risk review failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "reviewed":
        raise AssertionError(f"Expected risk review status='reviewed', got: {data}")

    return data


def _post_transition_risk_entry(client: TestClient, entry: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/risk/transition",
        json={
            "entry": entry,
            "new_status": "Monitoring",
            "notes": "Status changed to Monitoring during probe.",
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Risk transition failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "transitioned":
        raise AssertionError(f"Expected risk transition status='transitioned', got: {data}")

    return data


def _assert_file_exists(path_str: str, label: str) -> Path:
    path = Path(path_str)
    if not path.exists():
        raise AssertionError(f"Expected {label} to exist, but it was missing: {path}")
    return path


def _load_json(path: Path, label: str) -> Any:
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception as exc:
        raise AssertionError(f"Failed to load {label} JSON from {path}: {exc}") from exc


def _load_jsonl(path: Path, label: str) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    try:
        with path.open("r", encoding="utf-8") as handle:
            for line in handle:
                stripped = line.strip()
                if not stripped:
                    continue
                rows.append(json.loads(stripped))
    except Exception as exc:
        raise AssertionError(f"Failed to load {label} JSONL from {path}: {exc}") from exc
    return rows


def _verify_risk_log(
    *,
    project_id: str,
    risk_id: str,
    linked_decision_id: str,
    linked_change_packet_id: str,
) -> Path:
    project_root = Path("AI_GO/state/contractor_builder_v1/projects/by_project") / project_id
    risks_path = project_root / "risk_register" / "risks.jsonl"

    _assert_file_exists(str(risks_path), "risk log")

    rows = _load_jsonl(risks_path, "risk log")
    if len(rows) < 3:
        raise AssertionError(
            f"Expected at least 3 risk log entries (create/review/transition), got {len(rows)}"
        )

    matching = [row for row in rows if row.get("risk_id") == risk_id]
    if len(matching) < 3:
        raise AssertionError(
            f"Expected at least 3 entries for risk_id={risk_id}, got {len(matching)}"
        )

    created = matching[0]
    reviewed = matching[1]
    transitioned = matching[-1]

    if created.get("status") != "Open":
        raise AssertionError(f"Created risk should start as Open, got: {created.get('status')}")

    if linked_decision_id not in list(created.get("linked_decision_ids", [])):
        raise AssertionError("Created risk missing linked decision id")

    if linked_change_packet_id not in list(created.get("linked_change_packet_ids", [])):
        raise AssertionError("Created risk missing linked change packet id")

    if not str(reviewed.get("last_reviewed", "")).strip():
        raise AssertionError("Reviewed risk should have last_reviewed set")

    if transitioned.get("status") != "Monitoring":
        raise AssertionError(
            f"Transitioned risk should be Monitoring, got: {transitioned.get('status')}"
        )

    return risks_path


def _verify_risk_receipt(
    *,
    receipt_path_str: str,
    expected_event_type: str,
    project_id: str,
    risk_id: str,
) -> Path:
    receipt_path = _assert_file_exists(receipt_path_str, f"{expected_event_type} receipt")
    receipt = _load_json(receipt_path, f"{expected_event_type} receipt")

    if receipt.get("module_id") != "risk_register":
        raise AssertionError(
            f"{expected_event_type} receipt module_id mismatch: {receipt.get('module_id')}"
        )

    if receipt.get("event_type") != expected_event_type:
        raise AssertionError(
            f"{expected_event_type} receipt event_type mismatch: {receipt.get('event_type')}"
        )

    if receipt.get("project_id") != project_id:
        raise AssertionError(
            f"{expected_event_type} receipt project_id mismatch: {receipt.get('project_id')} != {project_id}"
        )

    if receipt.get("risk_id") != risk_id:
        raise AssertionError(
            f"{expected_event_type} receipt risk_id mismatch: {receipt.get('risk_id')} != {risk_id}"
        )

    return receipt_path


def run_probe() -> Dict[str, Any]:
    app = _build_isolated_app()
    client = TestClient(app)

    project_payload = _build_project_create_payload()
    project_response = _post_create_project(client, project_payload)

    project_id = project_response.get("project_id")
    if not project_id:
        raise AssertionError(f"Missing project_id in project create response: {project_response}")

    baseline_lock = project_response.get("baseline_lock", {})
    baseline_refs = baseline_lock.get("baseline_refs", {})
    if not baseline_refs:
        raise AssertionError("Project create response missing baseline_lock.baseline_refs")

    workflow_response = _post_initialize_workflow(
        client,
        project_id=project_id,
        phase_templates=_build_phase_templates(),
    )

    phase_instances = workflow_response.get("phase_instances", [])
    if not phase_instances:
        raise AssertionError("Workflow initialize response returned no phase_instances")

    first_phase = phase_instances[0]
    phase_id = first_phase.get("phase_id")
    if not phase_id:
        raise AssertionError(f"First phase instance missing phase_id: {first_phase}")

    change_packet_kwargs = _build_change_packet_kwargs(
        project_id=project_id,
        phase_id=phase_id,
        budget_baseline_id=baseline_refs["budget_baseline_id"],
        schedule_baseline_id=baseline_refs["schedule_baseline_id"],
        compliance_snapshot_id=baseline_refs["compliance_snapshot_id"],
    )
    change_response = _post_create_change_packet(client, change_packet_kwargs)

    change_packet = change_response.get("packet", {})
    linked_change_packet_id = change_packet.get("change_packet_id")
    if not linked_change_packet_id:
        raise AssertionError(f"Missing linked change packet id in change response: {change_response}")

    decision_entry_kwargs = _build_decision_entry_kwargs(
        project_id=project_id,
        phase_id=phase_id,
        linked_change_packet_id=linked_change_packet_id,
        compliance_snapshot_id=baseline_refs["compliance_snapshot_id"],
        schedule_baseline_id=baseline_refs["schedule_baseline_id"],
        budget_baseline_id=baseline_refs["budget_baseline_id"],
    )
    decision_response = _post_create_decision_entry(client, decision_entry_kwargs)

    decision_entry = decision_response.get("entry", {})
    linked_decision_id = decision_entry.get("decision_id")
    if not linked_decision_id:
        raise AssertionError(f"Missing linked decision id in decision response: {decision_response}")

    risk_entry_kwargs = _build_risk_entry_kwargs(
        project_id=project_id,
        linked_decision_id=linked_decision_id,
        linked_change_packet_id=linked_change_packet_id,
    )
    risk_create_response = _post_create_risk_entry(client, risk_entry_kwargs)

    created_entry = risk_create_response.get("entry", {})
    risk_id = created_entry.get("risk_id")
    if not risk_id:
        raise AssertionError(f"Missing risk_id in create response: {risk_create_response}")

    risk_review_response = _post_review_risk_entry(client, created_entry)
    reviewed_entry = risk_review_response.get("entry", {})
    if reviewed_entry.get("risk_id") != risk_id:
        raise AssertionError("Reviewed risk entry lost original risk_id")

    risk_transition_response = _post_transition_risk_entry(client, reviewed_entry)
    transitioned_entry = risk_transition_response.get("entry", {})
    if transitioned_entry.get("risk_id") != risk_id:
        raise AssertionError("Transitioned risk entry lost original risk_id")

    risks_path = _verify_risk_log(
        project_id=project_id,
        risk_id=risk_id,
        linked_decision_id=linked_decision_id,
        linked_change_packet_id=linked_change_packet_id,
    )

    create_receipt_path = _verify_risk_receipt(
        receipt_path_str=risk_create_response.get("receipt_path", ""),
        expected_event_type="create_risk",
        project_id=project_id,
        risk_id=risk_id,
    )
    review_receipt_path = _verify_risk_receipt(
        receipt_path_str=risk_review_response.get("receipt_path", ""),
        expected_event_type="review_risk",
        project_id=project_id,
        risk_id=risk_id,
    )
    transition_receipt_path = _verify_risk_receipt(
        receipt_path_str=risk_transition_response.get("receipt_path", ""),
        expected_event_type="change_risk_status",
        project_id=project_id,
        risk_id=risk_id,
    )

    summary = {
        "probe": "stage_contractor_risk_probe",
        "mode": "isolated_router_only",
        "status": "passed",
        "project_id": project_id,
        "phase_id": phase_id,
        "linked_change_packet_id": linked_change_packet_id,
        "linked_decision_id": linked_decision_id,
        "risk_id": risk_id,
        "verified_paths": {
            "risk_log": str(risks_path),
            "create_risk_receipt": str(create_receipt_path),
            "review_risk_receipt": str(review_receipt_path),
            "change_risk_status_receipt": str(transition_receipt_path),
        },
        "response_summary": {
            "create_status": risk_create_response.get("status"),
            "review_status": risk_review_response.get("status"),
            "transition_status": risk_transition_response.get("status"),
            "final_risk_status": transitioned_entry.get("status"),
            "project_name": project_payload["project_name"],
            "risk_category": risk_entry_kwargs["category"],
        },
    }
    return summary


def main() -> None:
    try:
        result = run_probe()
        print(json.dumps(result, indent=2, ensure_ascii=False))
        print("STAGE_CONTRACTOR_RISK_PROBE: PASS")
    except Exception as exc:
        print(f"STAGE_CONTRACTOR_RISK_PROBE: FAIL\n{exc}", file=sys.stderr)
        raise


if __name__ == "__main__":
    main()