from __future__ import annotations

"""
stage_contractor_project_intake_probe.py

Purpose:
- Exercise the contractor_builder_v1 project intake API surface in isolation
- Verify that project intake creates:
  - project_profile.json
  - baseline_lock.json
  - intake receipts
- Fail loudly if the contractor intake chain is broken

Usage examples:
    python -m AI_GO.tests.stage_contractor_project_intake_probe
    python AI_GO/tests/stage_contractor_project_intake_probe.py

Notes:
- This is a probe, not a mocked unit test.
- It does NOT import the full AI_GO app.
- It mounts only the contractor_builder_v1 router into a local FastAPI app.
"""

import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Dict, Tuple

from fastapi import FastAPI
from fastapi.testclient import TestClient


def _build_isolated_app() -> FastAPI:
    """
    Build a tiny isolated FastAPI app that mounts only the contractor router.
    This avoids unrelated router import failures elsewhere in the main app.
    """
    try:
        from AI_GO.api.contractor_builder_api import router as contractor_builder_router
    except Exception as exc:
        raise RuntimeError(
            "Unable to import isolated contractor builder router: "
            f"{exc}"
        ) from exc

    app = FastAPI(title="contractor_builder_v1_probe_app")
    app.include_router(contractor_builder_router)
    return app


def _now_compact() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")


def _build_request_payload() -> Dict[str, Any]:
    """
    Build a unique, valid contractor project intake request.
    """
    unique = _now_compact()

    return {
        "project_name": f"Contractor Intake Probe {unique}",
        "project_type": "Kitchen Remodel",
        "client_name": "Probe Client",
        "pm_name": "Probe PM",
        "jurisdiction": {
            "jurisdiction_id": "scottsburg-in",
            "authority_name": "Scottsburg Building Department",
            "city": "Scottsburg",
            "county": "Scott",
            "state": "IN",
        },
        "baseline_refs": {
            "schedule_baseline_id": f"schedule-baseline-{unique}",
            "budget_baseline_id": f"budget-baseline-{unique}",
            "compliance_snapshot_id": f"compliance-snapshot-{unique}",
        },
        "project_description": "Probe-created project for contractor_builder_v1 intake verification.",
        "client_contact": "probe-client@example.com",
        "pm_contact": "probe-pm@example.com",
        "site_address": "123 Probe Lane, Scottsburg, IN",
        "portfolio_id": "portfolio-probe",
        "oracle_snapshot_id": "",
        "exposure_profile_id": "",
        "notes": "Generated by isolated stage_contractor_project_intake_probe.py",
    }


def _post_create_project(client: TestClient, payload: Dict[str, Any]) -> Dict[str, Any]:
    """
    Call the contractor project create endpoint.
    """
    response = client.post("/contractor-builder/projects/create", json=payload)

    if response.status_code != 200:
        raise AssertionError(
            "Project create failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    try:
        data = response.json()
    except Exception as exc:
        raise AssertionError(f"Response was not valid JSON: {exc}") from exc

    if data.get("status") != "created":
        raise AssertionError(f"Expected status='created', got: {data}")

    return data


def _assert_file_exists(path_str: str, label: str) -> Path:
    """
    Assert that a path exists and return it as Path.
    """
    path = Path(path_str)
    if not path.exists():
        raise AssertionError(f"Expected {label} to exist, but it was missing: {path}")
    return path


def _load_json(path: Path, label: str) -> Dict[str, Any]:
    """
    Load a JSON file and fail loudly if invalid.
    """
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception as exc:
        raise AssertionError(f"Failed to load {label} JSON from {path}: {exc}") from exc


def _verify_project_files(
    project_id: str,
    payload: Dict[str, Any],
) -> Tuple[Path, Path]:
    """
    Verify project_profile.json and baseline_lock.json exist and contain expected values.
    """
    project_root = Path("AI_GO/state/contractor_builder_v1/projects/by_project") / project_id
    profile_path = project_root / "project_profile.json"
    baseline_path = project_root / "baseline_lock.json"

    _assert_file_exists(str(profile_path), "project profile")
    _assert_file_exists(str(baseline_path), "baseline lock")

    profile = _load_json(profile_path, "project profile")
    baseline = _load_json(baseline_path, "baseline lock")

    if profile.get("project_id") != project_id:
        raise AssertionError(
            f"project_profile.json project_id mismatch: {profile.get('project_id')} != {project_id}"
        )

    if profile.get("project_name") != payload["project_name"]:
        raise AssertionError(
            f"project_profile.json project_name mismatch: {profile.get('project_name')} != {payload['project_name']}"
        )

    if profile.get("project_type") != payload["project_type"]:
        raise AssertionError(
            f"project_profile.json project_type mismatch: {profile.get('project_type')} != {payload['project_type']}"
        )

    if profile.get("client", {}).get("name") != payload["client_name"]:
        raise AssertionError(
            "project_profile.json client.name mismatch: "
            f"{profile.get('client', {}).get('name')} != {payload['client_name']}"
        )

    if profile.get("pm", {}).get("name") != payload["pm_name"]:
        raise AssertionError(
            "project_profile.json pm.name mismatch: "
            f"{profile.get('pm', {}).get('name')} != {payload['pm_name']}"
        )

    baseline_refs = baseline.get("baseline_refs", {})
    expected_refs = payload["baseline_refs"]

    if baseline.get("project_id") != project_id:
        raise AssertionError(
            f"baseline_lock.json project_id mismatch: {baseline.get('project_id')} != {project_id}"
        )

    if baseline.get("lock_status") != "locked":
        raise AssertionError(
            f"baseline_lock.json lock_status mismatch: {baseline.get('lock_status')} != 'locked'"
        )

    for key, expected_value in expected_refs.items():
        if baseline_refs.get(key) != expected_value:
            raise AssertionError(
                f"baseline_lock.json baseline_refs[{key}] mismatch: "
                f"{baseline_refs.get(key)} != {expected_value}"
            )

    return profile_path, baseline_path


def _verify_receipts(project_id: str, response_data: Dict[str, Any]) -> Tuple[Path, Path]:
    """
    Verify the create_project and lock_baseline receipts exist and are internally consistent.
    """
    receipts = response_data.get("receipts", {})
    create_receipt_path = _assert_file_exists(
        receipts.get("create_project", ""),
        "create_project receipt",
    )
    lock_receipt_path = _assert_file_exists(
        receipts.get("lock_baseline", ""),
        "lock_baseline receipt",
    )

    create_receipt = _load_json(create_receipt_path, "create_project receipt")
    lock_receipt = _load_json(lock_receipt_path, "lock_baseline receipt")

    if create_receipt.get("module_id") != "project_intake":
        raise AssertionError(
            f"create_project receipt module_id mismatch: {create_receipt.get('module_id')}"
        )

    if create_receipt.get("event_type") != "create_project":
        raise AssertionError(
            f"create_project receipt event_type mismatch: {create_receipt.get('event_type')}"
        )

    if lock_receipt.get("event_type") != "lock_baseline":
        raise AssertionError(
            f"lock_baseline receipt event_type mismatch: {lock_receipt.get('event_type')}"
        )

    if create_receipt.get("project_id") != project_id:
        raise AssertionError(
            f"create_project receipt project_id mismatch: {create_receipt.get('project_id')} != {project_id}"
        )

    if lock_receipt.get("project_id") != project_id:
        raise AssertionError(
            f"lock_baseline receipt project_id mismatch: {lock_receipt.get('project_id')} != {project_id}"
        )

    return create_receipt_path, lock_receipt_path


def run_probe() -> Dict[str, Any]:
    """
    Execute the isolated contractor project intake probe and return a summary payload.
    """
    app = _build_isolated_app()
    client = TestClient(app)

    payload = _build_request_payload()
    response_data = _post_create_project(client, payload)

    project_id = response_data.get("project_id")
    if not project_id:
        raise AssertionError(f"Missing project_id in create response: {response_data}")

    profile_path, baseline_path = _verify_project_files(project_id, payload)
    create_receipt_path, lock_receipt_path = _verify_receipts(project_id, response_data)

    summary = {
        "probe": "stage_contractor_project_intake_probe",
        "mode": "isolated_router_only",
        "status": "passed",
        "project_id": project_id,
        "verified_paths": {
            "project_profile": str(profile_path),
            "baseline_lock": str(baseline_path),
            "create_project_receipt": str(create_receipt_path),
            "lock_baseline_receipt": str(lock_receipt_path),
        },
        "response_summary": {
            "status": response_data.get("status"),
            "project_name": payload["project_name"],
            "project_type": payload["project_type"],
        },
    }
    return summary


def main() -> None:
    """
    Console entrypoint.
    """
    try:
        result = run_probe()
        print(json.dumps(result, indent=2, ensure_ascii=False))
        print("STAGE_CONTRACTOR_PROJECT_INTAKE_PROBE: PASS")
    except Exception as exc:
        print(f"STAGE_CONTRACTOR_PROJECT_INTAKE_PROBE: FAIL\n{exc}", file=sys.stderr)
        raise


if __name__ == "__main__":
    main()