from __future__ import annotations

"""
stage_contractor_oracle_probe.py

Purpose:
- Exercise the contractor_builder_v1 oracle API surface in isolation
- Verify that the oracle branch can:
  - create a real project
  - list bounded registered snapshots
  - publish a known snapshot through the API flow
  - classify a shock record
  - build a project exposure profile
  - build an oracle projection
  - build a risk radar
  - build a procurement advisory
  - emit an oracle receipt

Usage examples:
    python -m AI_GO.tests.stage_contractor_oracle_probe
    python AI_GO/tests/stage_contractor_oracle_probe.py

Notes:
- This is a probe, not a mocked unit test.
- It mounts only the contractor_builder_v1 router into a local FastAPI app.
- It uses the bounded in-repo oracle registry, not live market data.
"""

import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Dict, List

from fastapi import FastAPI
from fastapi.testclient import TestClient


def _build_isolated_app() -> FastAPI:
    try:
        from AI_GO.api.contractor_builder_api import router as contractor_builder_router
    except Exception as exc:
        raise RuntimeError(
            "Unable to import isolated contractor builder router: "
            f"{exc}"
        ) from exc

    app = FastAPI(title="contractor_builder_v1_oracle_probe_app")
    app.include_router(contractor_builder_router)
    return app


def _now_compact() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")


def _build_project_create_payload() -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "project_name": f"Contractor Oracle Probe {unique}",
        "project_type": "Kitchen Remodel",
        "client_name": "Oracle Probe Client",
        "pm_name": "Oracle Probe PM",
        "jurisdiction": {
            "jurisdiction_id": "scottsburg-in",
            "authority_name": "Scottsburg Building Department",
            "city": "Scottsburg",
            "county": "Scott",
            "state": "IN",
        },
        "baseline_refs": {
            "schedule_baseline_id": f"schedule-baseline-{unique}",
            "budget_baseline_id": f"budget-baseline-{unique}",
            "compliance_snapshot_id": f"compliance-snapshot-{unique}",
        },
        "project_description": "Probe-created project for contractor oracle verification.",
        "client_contact": "oracle-probe-client@example.com",
        "pm_contact": "oracle-probe-pm@example.com",
        "site_address": "159 Oracle Lane, Scottsburg, IN",
        "portfolio_id": "portfolio-oracle-probe",
        "oracle_snapshot_id": "snapshot-lumber-watch",
        "exposure_profile_id": f"exposure-profile-{unique}",
        "notes": "Generated by stage_contractor_oracle_probe.py",
    }


def _post_create_project(client: Any, payload: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post("/contractor-builder/projects/create", json=payload)

    if response.status_code != 200:
        raise AssertionError(
            "Project create failed during oracle probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected project create status='created', got: {data}")

    return data


def _get_oracle_snapshots(client: Any) -> Dict[str, Any]:
    response = client.get("/contractor-builder/oracle/snapshots")

    if response.status_code != 200:
        raise AssertionError(
            "Oracle snapshots request failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "ok":
        raise AssertionError(f"Expected oracle/snapshots status='ok', got: {data}")

    return data


def _post_project_external_pressure(
    client: Any,
    *,
    project_id: str,
    snapshot_id: str,
    exposure_profile_id: str,
    domain_exposure: Dict[str, str],
) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/oracle/project-external-pressure",
        json={
            "project_id": project_id,
            "snapshot_id": snapshot_id,
            "exposure_profile_id": exposure_profile_id,
            "domain_exposure": domain_exposure,
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Oracle project-external-pressure failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "ok":
        raise AssertionError(
            f"Expected oracle/project-external-pressure status='ok', got: {data}"
        )

    return data


def _assert_file_exists(path_str: str, label: str) -> Path:
    path = Path(path_str)
    if not path.exists():
        raise AssertionError(f"Expected {label} to exist, but it was missing: {path}")
    return path


def _load_json(path: Path, label: str) -> Any:
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception as exc:
        raise AssertionError(f"Failed to load {label} JSON from {path}: {exc}") from exc


def _verify_snapshot_list(snapshots_response: Dict[str, Any], snapshot_id: str) -> None:
    snapshots = snapshots_response.get("snapshots", [])
    if not isinstance(snapshots, list) or not snapshots:
        raise AssertionError("Expected non-empty oracle snapshots list")

    snapshot_ids = {str(item.get("snapshot_id", "")) for item in snapshots}
    if snapshot_id not in snapshot_ids:
        raise AssertionError(
            f"Expected snapshot_id {snapshot_id} in oracle snapshots, got: {snapshot_ids}"
        )


def _verify_oracle_response(
    *,
    project_id: str,
    snapshot_id: str,
    exposure_profile_id: str,
    oracle_response: Dict[str, Any],
) -> tuple[Path, Dict[str, Any]]:
    snapshot = oracle_response.get("snapshot", {})
    shock = oracle_response.get("shock", {})
    exposure_profile = oracle_response.get("exposure_profile", {})
    projection = oracle_response.get("projection", {})
    risk_radar = oracle_response.get("risk_radar", {})
    procurement_advisory = oracle_response.get("procurement_advisory", {})
    receipt = oracle_response.get("receipt", {})

    if snapshot.get("snapshot_id") != snapshot_id:
        raise AssertionError(
            f"snapshot_id mismatch: {snapshot.get('snapshot_id')} != {snapshot_id}"
        )

    if snapshot.get("market_domain") != "Lumber":
        raise AssertionError(
            f"Expected Lumber market_domain, got: {snapshot.get('market_domain')}"
        )

    if shock.get("snapshot_id") != snapshot_id:
        raise AssertionError(
            f"shock snapshot_id mismatch: {shock.get('snapshot_id')} != {snapshot_id}"
        )

    if shock.get("market_domain") != "Lumber":
        raise AssertionError(
            f"shock market_domain mismatch: {shock.get('market_domain')}"
        )

    if str(shock.get("shock_direction", "")).strip() not in {"up", "down", "flat"}:
        raise AssertionError(
            f"Unexpected shock_direction: {shock.get('shock_direction')}"
        )

    if str(shock.get("shock_severity", "")).strip() not in {"none", "low", "moderate", "high"}:
        raise AssertionError(
            f"Unexpected shock_severity: {shock.get('shock_severity')}"
        )

    if exposure_profile.get("project_id") != project_id:
        raise AssertionError(
            f"exposure_profile project_id mismatch: {exposure_profile.get('project_id')} != {project_id}"
        )

    if exposure_profile.get("exposure_profile_id") != exposure_profile_id:
        raise AssertionError(
            "exposure_profile_id mismatch: "
            f"{exposure_profile.get('exposure_profile_id')} != {exposure_profile_id}"
        )

    if exposure_profile.get("domain_exposure", {}).get("Lumber") != "High":
        raise AssertionError("Expected Lumber exposure level High")

    if projection.get("project_id") != project_id:
        raise AssertionError(
            f"projection project_id mismatch: {projection.get('project_id')} != {project_id}"
        )

    if projection.get("snapshot_id") != snapshot_id:
        raise AssertionError(
            f"projection snapshot_id mismatch: {projection.get('snapshot_id')} != {snapshot_id}"
        )

    if projection.get("market_domain") != "Lumber":
        raise AssertionError(
            f"projection market_domain mismatch: {projection.get('market_domain')}"
        )

    if str(projection.get("projected_pressure_label", "")).strip() not in {
        "stable",
        "watch",
        "elevated",
        "acute",
    }:
        raise AssertionError(
            f"Unexpected projected_pressure_label: {projection.get('projected_pressure_label')}"
        )

    if str(projection.get("projected_cost_risk_label", "")).strip() not in {
        "Low",
        "Moderate",
        "High",
    }:
        raise AssertionError(
            f"Unexpected projected_cost_risk_label: {projection.get('projected_cost_risk_label')}"
        )

    if str(projection.get("projected_schedule_risk_label", "")).strip() not in {
        "Low",
        "Moderate",
        "High",
    }:
        raise AssertionError(
            f"Unexpected projected_schedule_risk_label: {projection.get('projected_schedule_risk_label')}"
        )

    if risk_radar.get("project_id") != project_id:
        raise AssertionError(
            f"risk_radar project_id mismatch: {risk_radar.get('project_id')} != {project_id}"
        )

    if str(risk_radar.get("summary_label", "")).strip() not in {
        "stable_external_pressure",
        "watch_external_pressure",
        "elevated_external_pressure",
    }:
        raise AssertionError(
            f"Unexpected risk_radar summary_label: {risk_radar.get('summary_label')}"
        )

    if procurement_advisory.get("project_id") != project_id:
        raise AssertionError(
            f"procurement_advisory project_id mismatch: {procurement_advisory.get('project_id')} != {project_id}"
        )

    if procurement_advisory.get("market_domain") != "Lumber":
        raise AssertionError(
            "procurement_advisory market_domain mismatch: "
            f"{procurement_advisory.get('market_domain')}"
        )

    if str(procurement_advisory.get("procurement_posture", "")).strip() not in {
        "Hold",
        "Watch",
        "Advance_Buy",
        "Escalate_For_PM",
    }:
        raise AssertionError(
            f"Unexpected procurement_posture: {procurement_advisory.get('procurement_posture')}"
        )

    if receipt.get("module_id") != "oracle":
        raise AssertionError(f"oracle receipt module_id mismatch: {receipt.get('module_id')}")

    if receipt.get("event_type") != "create_projection":
        raise AssertionError(f"oracle receipt event_type mismatch: {receipt.get('event_type')}")

    if receipt.get("project_id") != project_id:
        raise AssertionError(
            f"oracle receipt project_id mismatch: {receipt.get('project_id')} != {project_id}"
        )

    receipt_path = _assert_file_exists(
        oracle_response.get("receipt_path", ""),
        "oracle create_projection receipt",
    )
    persisted_receipt = _load_json(receipt_path, "oracle create_projection receipt")

    if persisted_receipt.get("receipt_id") != receipt.get("receipt_id"):
        raise AssertionError("Persisted oracle receipt_id does not match inline receipt")

    return receipt_path, projection


def run_probe() -> Dict[str, Any]:
    app = _build_isolated_app()
    client = TestClient(app)

    project_payload = _build_project_create_payload()
    project_response = _post_create_project(client, project_payload)

    project_id = project_response.get("project_id")
    if not project_id:
        raise AssertionError(f"Missing project_id in project create response: {project_response}")

    snapshot_id = project_payload["oracle_snapshot_id"]
    exposure_profile_id = project_payload["exposure_profile_id"]

    snapshots_response = _get_oracle_snapshots(client)
    _verify_snapshot_list(snapshots_response, snapshot_id)

    domain_exposure = {
        "Lumber": "High",
        "Steel": "Low",
        "Fuel": "Moderate",
    }

    oracle_response = _post_project_external_pressure(
        client,
        project_id=project_id,
        snapshot_id=snapshot_id,
        exposure_profile_id=exposure_profile_id,
        domain_exposure=domain_exposure,
    )

    receipt_path, projection = _verify_oracle_response(
        project_id=project_id,
        snapshot_id=snapshot_id,
        exposure_profile_id=exposure_profile_id,
        oracle_response=oracle_response,
    )

    summary = {
        "probe": "stage_contractor_oracle_probe",
        "mode": "isolated_router_only",
        "status": "passed",
        "project_id": project_id,
        "snapshot_id": snapshot_id,
        "exposure_profile_id": exposure_profile_id,
        "verified_paths": {
            "oracle_receipt": str(receipt_path),
        },
        "response_summary": {
            "snapshots_status": snapshots_response.get("status"),
            "oracle_status": oracle_response.get("status"),
            "project_name": project_payload["project_name"],
            "market_domain": oracle_response.get("snapshot", {}).get("market_domain"),
            "shock_direction": oracle_response.get("shock", {}).get("shock_direction"),
            "shock_severity": oracle_response.get("shock", {}).get("shock_severity"),
            "projected_pressure_label": projection.get("projected_pressure_label"),
            "projected_cost_risk_label": projection.get("projected_cost_risk_label"),
            "projected_schedule_risk_label": projection.get("projected_schedule_risk_label"),
            "procurement_posture": oracle_response.get("procurement_advisory", {}).get("procurement_posture"),
        },
    }
    return summary


def main() -> None:
    try:
        result = run_probe()
        print(json.dumps(result, indent=2, ensure_ascii=False))
        print("STAGE_CONTRACTOR_ORACLE_PROBE: PASS")
    except Exception as exc:
        print(f"STAGE_CONTRACTOR_ORACLE_PROBE: FAIL\n{exc}", file=sys.stderr)
        raise


if __name__ == "__main__":
    main()