from __future__ import annotations

"""
stage_contractor_workflow_probe.py

Purpose:
- Exercise the contractor_builder_v1 workflow API surface in isolation
- Verify that workflow initialization creates:
  - workflow/phase_instances.json
  - workflow/phase_history.jsonl
  - workflow receipt for create_phase_plan
- Reuse a real project created through the contractor projects API

Usage examples:
    python -m AI_GO.tests.stage_contractor_workflow_probe
    python AI_GO/tests/stage_contractor_workflow_probe.py

Notes:
- This is a probe, not a mocked unit test.
- It mounts only the contractor_builder_v1 router into a local FastAPI app.
- It first creates a real project, then initializes workflow against that project.
"""

import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Dict, List, Tuple

from fastapi import FastAPI
from fastapi.testclient import TestClient


def _build_isolated_app() -> FastAPI:
    """
    Build a tiny isolated FastAPI app that mounts only the contractor router.
    """
    try:
        from AI_GO.api.contractor_builder_api import router as contractor_builder_router
    except Exception as exc:
        raise RuntimeError(
            "Unable to import isolated contractor builder router: "
            f"{exc}"
        ) from exc

    app = FastAPI(title="contractor_builder_v1_workflow_probe_app")
    app.include_router(contractor_builder_router)
    return app


def _now_compact() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")


def _build_project_create_payload() -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "project_name": f"Contractor Workflow Probe {unique}",
        "project_type": "Kitchen Remodel",
        "client_name": "Workflow Probe Client",
        "pm_name": "Workflow Probe PM",
        "jurisdiction": {
            "jurisdiction_id": "scottsburg-in",
            "authority_name": "Scottsburg Building Department",
            "city": "Scottsburg",
            "county": "Scott",
            "state": "IN",
        },
        "baseline_refs": {
            "schedule_baseline_id": f"schedule-baseline-{unique}",
            "budget_baseline_id": f"budget-baseline-{unique}",
            "compliance_snapshot_id": f"compliance-snapshot-{unique}",
        },
        "project_description": "Probe-created project for contractor workflow verification.",
        "client_contact": "workflow-probe-client@example.com",
        "pm_contact": "workflow-probe-pm@example.com",
        "site_address": "456 Workflow Lane, Scottsburg, IN",
        "portfolio_id": "portfolio-workflow-probe",
        "oracle_snapshot_id": "",
        "exposure_profile_id": "",
        "notes": "Generated by stage_contractor_workflow_probe.py",
    }


def _build_phase_templates() -> List[Dict[str, Any]]:
    return [
        {
            "template_id": "template-demo-demolition",
            "project_type": "Kitchen Remodel",
            "phase_name": "Demolition",
            "expected_duration_days": 3,
            "dependencies": [],
            "role_expectations": {
                "crew": ["demo crew"],
                "management": ["pm oversight"],
            },
            "management_checkpoints": ["site protection verified"],
            "client_gate_requirement": {
                "required": False,
                "checklist": [],
            },
            "notes": "Initial demolition phase.",
        },
        {
            "template_id": "template-demo-framing",
            "project_type": "Kitchen Remodel",
            "phase_name": "Framing",
            "expected_duration_days": 5,
            "dependencies": ["Demolition"],
            "role_expectations": {
                "crew": ["carpentry crew"],
                "management": ["pm walkthrough"],
            },
            "management_checkpoints": ["framing layout reviewed"],
            "client_gate_requirement": {
                "required": True,
                "checklist": ["layout approved"],
            },
            "notes": "Framing follows demolition.",
        },
    ]


def _post_create_project(client: TestClient, payload: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post("/contractor-builder/projects/create", json=payload)

    if response.status_code != 200:
        raise AssertionError(
            "Project create failed during workflow probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected project create status='created', got: {data}")

    return data


def _post_initialize_workflow(
    client: TestClient,
    project_id: str,
    phase_templates: List[Dict[str, Any]],
) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/workflow/initialize",
        json={
            "project_id": project_id,
            "phase_templates": phase_templates,
            "overwrite": False,
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Workflow initialize failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "initialized":
        raise AssertionError(f"Expected workflow status='initialized', got: {data}")

    return data


def _assert_file_exists(path_str: str, label: str) -> Path:
    path = Path(path_str)
    if not path.exists():
        raise AssertionError(f"Expected {label} to exist, but it was missing: {path}")
    return path


def _load_json(path: Path, label: str) -> Any:
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception as exc:
        raise AssertionError(f"Failed to load {label} JSON from {path}: {exc}") from exc


def _verify_workflow_files(
    project_id: str,
    workflow_response: Dict[str, Any],
    phase_templates: List[Dict[str, Any]],
) -> Tuple[Path, Path]:
    project_root = Path("AI_GO/state/contractor_builder_v1/projects/by_project") / project_id
    phase_instances_path = project_root / "workflow" / "phase_instances.json"
    phase_history_path = project_root / "workflow" / "phase_history.jsonl"

    _assert_file_exists(str(phase_instances_path), "phase instances")
    _assert_file_exists(str(phase_history_path), "phase history log")

    phase_instances = _load_json(phase_instances_path, "phase instances")
    if not isinstance(phase_instances, list):
        raise AssertionError("phase_instances.json should contain a list of phase instances")

    if len(phase_instances) != len(phase_templates):
        raise AssertionError(
            f"Phase instance count mismatch: {len(phase_instances)} != {len(phase_templates)}"
        )

    workflow_state = workflow_response.get("workflow_state", {})
    if workflow_state.get("project_id") != project_id:
        raise AssertionError(
            f"workflow_state.project_id mismatch: {workflow_state.get('project_id')} != {project_id}"
        )

    if int(workflow_state.get("phase_count", -1)) != len(phase_templates):
        raise AssertionError(
            f"workflow_state.phase_count mismatch: {workflow_state.get('phase_count')} != {len(phase_templates)}"
        )

    for instance in phase_instances:
        if instance.get("project_id") != project_id:
            raise AssertionError(
                f"phase instance project_id mismatch: {instance.get('project_id')} != {project_id}"
            )
        if instance.get("phase_status") != "not_started":
            raise AssertionError(
                f"phase instance should start as not_started, got: {instance.get('phase_status')}"
            )
        if not instance.get("phase_id"):
            raise AssertionError("phase instance missing phase_id")
        if not instance.get("template_id"):
            raise AssertionError("phase instance missing template_id")
        if not instance.get("phase_name"):
            raise AssertionError("phase instance missing phase_name")

    return phase_instances_path, phase_history_path


def _verify_workflow_receipt(
    project_id: str,
    workflow_response: Dict[str, Any],
    phase_templates: List[Dict[str, Any]],
) -> Path:
    receipt_path = _assert_file_exists(
        workflow_response.get("receipt_path", ""),
        "workflow create_phase_plan receipt",
    )
    receipt = _load_json(receipt_path, "workflow receipt")

    if receipt.get("module_id") != "workflow":
        raise AssertionError(
            f"workflow receipt module_id mismatch: {receipt.get('module_id')}"
        )

    if receipt.get("event_type") != "create_phase_plan":
        raise AssertionError(
            f"workflow receipt event_type mismatch: {receipt.get('event_type')}"
        )

    if receipt.get("project_id") != project_id:
        raise AssertionError(
            f"workflow receipt project_id mismatch: {receipt.get('project_id')} != {project_id}"
        )

    details = receipt.get("details", {})
    if int(details.get("phase_count", -1)) != len(phase_templates):
        raise AssertionError(
            f"workflow receipt phase_count mismatch: {details.get('phase_count')} != {len(phase_templates)}"
        )

    return receipt_path


def run_probe() -> Dict[str, Any]:
    app = _build_isolated_app()
    client = TestClient(app)

    project_payload = _build_project_create_payload()
    project_response = _post_create_project(client, project_payload)
    project_id = project_response.get("project_id")
    if not project_id:
        raise AssertionError(f"Missing project_id in project create response: {project_response}")

    phase_templates = _build_phase_templates()
    workflow_response = _post_initialize_workflow(client, project_id, phase_templates)

    phase_instances_path, phase_history_path = _verify_workflow_files(
        project_id=project_id,
        workflow_response=workflow_response,
        phase_templates=phase_templates,
    )
    workflow_receipt_path = _verify_workflow_receipt(
        project_id=project_id,
        workflow_response=workflow_response,
        phase_templates=phase_templates,
    )

    summary = {
        "probe": "stage_contractor_workflow_probe",
        "mode": "isolated_router_only",
        "status": "passed",
        "project_id": project_id,
        "verified_paths": {
            "phase_instances": str(phase_instances_path),
            "phase_history": str(phase_history_path),
            "workflow_receipt": str(workflow_receipt_path),
        },
        "response_summary": {
            "status": workflow_response.get("status"),
            "phase_count": workflow_response.get("workflow_state", {}).get("phase_count"),
            "project_name": project_payload["project_name"],
            "project_type": project_payload["project_type"],
        },
    }
    return summary


def main() -> None:
    try:
        result = run_probe()
        print(json.dumps(result, indent=2, ensure_ascii=False))
        print("STAGE_CONTRACTOR_WORKFLOW_PROBE: PASS")
    except Exception as exc:
        print(f"STAGE_CONTRACTOR_WORKFLOW_PROBE: FAIL\n{exc}", file=sys.stderr)
        raise


if __name__ == "__main__":
    main()