from __future__ import annotations

"""
stage_contractor_assumption_probe.py

Purpose:
- Exercise the contractor_builder_v1 assumption API surface in isolation
- Verify that the assumption_log branch can:
  - create a real project
  - initialize workflow
  - create a lawful linked change packet
  - create a lawful linked decision entry
  - create a lawful linked risk entry
  - create a lawful assumption entry
  - transition the assumption entry status
  - invalidate the assumption entry with a lawful conversion record
  - append assumption records to assumption_log/assumptions.jsonl
  - emit assumption receipts for create/transition/invalidate

Usage examples:
    python -m AI_GO.tests.stage_contractor_assumption_probe
    python AI_GO/tests/stage_contractor_assumption_probe.py
"""

import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Dict, List

from fastapi import FastAPI
from fastapi.testclient import TestClient


def _build_isolated_app() -> FastAPI:
    try:
        from AI_GO.api.contractor_builder_api import router as contractor_builder_router
    except Exception as exc:
        raise RuntimeError(
            "Unable to import isolated contractor builder router: "
            f"{exc}"
        ) from exc

    app = FastAPI(title="contractor_builder_v1_assumption_probe_app")
    app.include_router(contractor_builder_router)
    return app


def _now_compact() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")


def _build_project_create_payload() -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "project_name": f"Contractor Assumption Probe {unique}",
        "project_type": "Kitchen Remodel",
        "client_name": "Assumption Probe Client",
        "pm_name": "Assumption Probe PM",
        "jurisdiction": {
            "jurisdiction_id": "scottsburg-in",
            "authority_name": "Scottsburg Building Department",
            "city": "Scottsburg",
            "county": "Scott",
            "state": "IN",
        },
        "baseline_refs": {
            "schedule_baseline_id": f"schedule-baseline-{unique}",
            "budget_baseline_id": f"budget-baseline-{unique}",
            "compliance_snapshot_id": f"compliance-snapshot-{unique}",
        },
        "project_description": "Probe-created project for contractor assumption verification.",
        "client_contact": "assumption-probe-client@example.com",
        "pm_contact": "assumption-probe-pm@example.com",
        "site_address": "987 Assumption Lane, Scottsburg, IN",
        "portfolio_id": "portfolio-assumption-probe",
        "oracle_snapshot_id": "",
        "exposure_profile_id": "",
        "notes": "Generated by stage_contractor_assumption_probe.py",
    }


def _build_phase_templates() -> List[Dict[str, Any]]:
    return [
        {
            "template_id": "template-assumption-demolition",
            "project_type": "Kitchen Remodel",
            "phase_name": "Demolition",
            "expected_duration_days": 3,
            "dependencies": [],
            "role_expectations": {
                "crew": ["demo crew"],
                "management": ["pm oversight"],
            },
            "management_checkpoints": ["site protection verified"],
            "client_gate_requirement": {
                "required": False,
                "checklist": [],
            },
            "notes": "Initial demolition phase.",
        }
    ]


def _post_create_project(client: TestClient, payload: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post("/contractor-builder/projects/create", json=payload)

    if response.status_code != 200:
        raise AssertionError(
            "Project create failed during assumption probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected project create status='created', got: {data}")

    return data


def _post_initialize_workflow(
    client: TestClient,
    project_id: str,
    phase_templates: List[Dict[str, Any]],
) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/workflow/initialize",
        json={
            "project_id": project_id,
            "phase_templates": phase_templates,
            "overwrite": False,
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Workflow initialize failed during assumption probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "initialized":
        raise AssertionError(f"Expected workflow status='initialized', got: {data}")

    return data


def _build_change_packet_kwargs(
    *,
    project_id: str,
    phase_id: str,
    budget_baseline_id: str,
    schedule_baseline_id: str,
    compliance_snapshot_id: str,
) -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "change_packet_id": f"change-packet-{unique}",
        "project_id": project_id,
        "phase_id": phase_id,
        "title": "Assumption probe linked change packet",
        "originator_name": "Assumption Probe PM",
        "originator_role": "Project Manager",
        "originator_org": "AI_GO Probe",
        "workflow_phase_state_snapshot_id": f"workflow-phase-snapshot-{unique}",
        "compliance_snapshot_id": compliance_snapshot_id,
        "drawing_revision_id": f"drawing-rev-{unique}",
        "budget_baseline_id": budget_baseline_id,
        "schedule_baseline_id": schedule_baseline_id,
        "scope_delta_description": "Linked change packet for assumption context.",
        "added_items": ["selective rework allowance"],
        "removed_items": [],
        "scope_notes": "Used only to provide assumption linkage context.",
        "phase_status": "not_started",
        "disruption_multiplier": 1.0,
        "factors_applied": ["assumption_probe_context"],
    }


def _post_create_change_packet(client: TestClient, packet_kwargs: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/change/create",
        json={"packet_kwargs": packet_kwargs},
    )

    if response.status_code != 200:
        raise AssertionError(
            "Change packet create failed during assumption probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected change create status='created', got: {data}")

    return data


def _build_decision_entry_kwargs(
    *,
    project_id: str,
    phase_id: str,
    linked_change_packet_id: str,
    compliance_snapshot_id: str,
    schedule_baseline_id: str,
    budget_baseline_id: str,
) -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "decision_id": f"decision-{unique}",
        "project_id": project_id,
        "title": "Proceed using assumed wall cavity clearance",
        "decision_type": "Scope_Clarification",
        "phase_id": phase_id,
        "linked_change_packet_id": linked_change_packet_id,
        "compliance_snapshot_id": compliance_snapshot_id,
        "schedule_baseline_id": schedule_baseline_id,
        "budget_baseline_id": budget_baseline_id,
        "drawing_revision_id": f"drawing-rev-{unique}",
        "oracle_snapshot_id": "",
        "expected_schedule_delta_days": 0.5,
        "expected_cost_delta_amount": 100.0,
        "expected_margin_delta_percent": None,
        "expected_risk_level": "Moderate",
        "notes_on_assumptions": "Decision depends on existing wall cavity condition remaining as observed.",
        "may_reference_in_owner_reports": True,
        "owner_report_reference_label": "wall_cavity_probe",
        "notes_internal": "Probe decision entry for assumption linkage.",
        "attachments_refs": [],
    }


def _post_create_decision_entry(client: TestClient, entry_kwargs: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/decision/create",
        json={"entry_kwargs": entry_kwargs},
    )

    if response.status_code != 200:
        raise AssertionError(
            "Decision create failed during assumption probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected decision create status='created', got: {data}")

    return data


def _build_risk_entry_kwargs(
    *,
    project_id: str,
    linked_decision_id: str,
    linked_change_packet_id: str,
) -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "risk_id": f"risk-{unique}",
        "project_id": project_id,
        "category": "Site_Conditions",
        "description": "Existing cavity conditions may differ from observed limited opening.",
        "probability": "Moderate",
        "impact_level": "Moderate",
        "mitigation_strategy": "Verify opening before full rough-in sequencing is committed.",
        "mitigation_owner": "Project Manager",
        "review_frequency": "weekly",
        "linked_decision_ids": [linked_decision_id],
        "linked_change_packet_ids": [linked_change_packet_id],
        "notes": "Probe risk entry for assumption linkage.",
    }


def _post_create_risk_entry(client: TestClient, entry_kwargs: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/risk/create",
        json={"entry_kwargs": entry_kwargs},
    )

    if response.status_code != 200:
        raise AssertionError(
            "Risk create failed during assumption probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected risk create status='created', got: {data}")

    return data


def _build_assumption_entry_kwargs(
    *,
    project_id: str,
    linked_decision_id: str,
    linked_change_packet_id: str,
    linked_risk_id: str,
) -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "assumption_id": f"assumption-{unique}",
        "project_id": project_id,
        "statement": "Existing wall cavity is clear enough to relocate outlet without opening adjacent section.",
        "source_type": "Site_Visit",
        "source_reference": f"site-walk-{unique}",
        "logged_by": "Assumption Probe PM",
        "owner_acknowledged": "Not_Required",
        "validation_status": "Unverified",
        "impact_if_false": "Could require additional demolition, resequencing, and change review.",
        "linked_decision_ids": [linked_decision_id],
        "linked_change_packet_ids": [linked_change_packet_id],
        "linked_risk_ids": [linked_risk_id],
        "notes": "Probe assumption entry for assumption_log verification.",
    }


def _post_create_assumption_entry(client: TestClient, entry_kwargs: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/assumption/create",
        json={"entry_kwargs": entry_kwargs},
    )

    if response.status_code != 200:
        raise AssertionError(
            "Assumption create failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected assumption create status='created', got: {data}")

    return data


def _post_transition_assumption_entry(client: TestClient, entry: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/assumption/transition",
        json={
            "entry": entry,
            "new_status": "Verified",
            "notes": "Status changed to Verified during probe.",
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Assumption transition failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "transitioned":
        raise AssertionError(f"Expected assumption transition status='transitioned', got: {data}")

    return data


def _post_invalidate_assumption_entry(
    client: TestClient,
    entry: Dict[str, Any],
    linked_decision_id: str,
    linked_change_packet_id: str,
    linked_risk_id: str,
) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/assumption/invalidate",
        json={
            "entry": entry,
            "actor_name": "Assumption Probe Reviewer",
            "actor_role": "Project Manager",
            "conversion_option": "Link_to_Risk",
            "linked_decision_id": linked_decision_id,
            "linked_change_packet_id": linked_change_packet_id,
            "linked_risk_id": linked_risk_id,
            "rationale": "Field verification contradicted the original cavity assumption.",
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Assumption invalidation failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "invalidated":
        raise AssertionError(f"Expected assumption invalidation status='invalidated', got: {data}")

    return data


def _assert_file_exists(path_str: str, label: str) -> Path:
    path = Path(path_str)
    if not path.exists():
        raise AssertionError(f"Expected {label} to exist, but it was missing: {path}")
    return path


def _load_json(path: Path, label: str) -> Any:
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception as exc:
        raise AssertionError(f"Failed to load {label} JSON from {path}: {exc}") from exc


def _load_jsonl(path: Path, label: str) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    try:
        with path.open("r", encoding="utf-8") as handle:
            for line in handle:
                stripped = line.strip()
                if not stripped:
                    continue
                rows.append(json.loads(stripped))
    except Exception as exc:
        raise AssertionError(f"Failed to load {label} JSONL from {path}: {exc}") from exc
    return rows


def _verify_assumption_log(
    *,
    project_id: str,
    assumption_id: str,
    linked_decision_id: str,
    linked_change_packet_id: str,
    linked_risk_id: str,
) -> Path:
    project_root = Path("AI_GO/state/contractor_builder_v1/projects/by_project") / project_id
    assumptions_path = project_root / "assumption_log" / "assumptions.jsonl"

    _assert_file_exists(str(assumptions_path), "assumption log")

    rows = _load_jsonl(assumptions_path, "assumption log")
    if len(rows) < 3:
        raise AssertionError(
            f"Expected at least 3 assumption log entries (create/transition/invalidate), got {len(rows)}"
        )

    matching = [row for row in rows if row.get("assumption_id") == assumption_id]
    if len(matching) < 3:
        raise AssertionError(
            f"Expected at least 3 entries for assumption_id={assumption_id}, got {len(matching)}"
        )

    created = matching[0]
    transitioned = matching[1]
    invalidated = matching[-1]

    if created.get("validation_status") != "Unverified":
        raise AssertionError(
            f"Created assumption should start as Unverified, got: {created.get('validation_status')}"
        )

    if linked_decision_id not in list(created.get("linked_decision_ids", [])):
        raise AssertionError("Created assumption missing linked decision id")

    if linked_change_packet_id not in list(created.get("linked_change_packet_ids", [])):
        raise AssertionError("Created assumption missing linked change packet id")

    if linked_risk_id not in list(created.get("linked_risk_ids", [])):
        raise AssertionError("Created assumption missing linked risk id")

    if transitioned.get("validation_status") != "Verified":
        raise AssertionError(
            f"Transitioned assumption should be Verified, got: {transitioned.get('validation_status')}"
        )

    if invalidated.get("validation_status") != "Invalidated":
        raise AssertionError(
            f"Invalidated assumption should be Invalidated, got: {invalidated.get('validation_status')}"
        )

    return assumptions_path


def _verify_assumption_receipt(
    *,
    receipt_path_str: str,
    expected_event_type: str,
    project_id: str,
    assumption_id: str,
) -> Path:
    receipt_path = _assert_file_exists(receipt_path_str, f"{expected_event_type} receipt")
    receipt = _load_json(receipt_path, f"{expected_event_type} receipt")

    if receipt.get("module_id") != "assumption_log":
        raise AssertionError(
            f"{expected_event_type} receipt module_id mismatch: {receipt.get('module_id')}"
        )

    if receipt.get("event_type") != expected_event_type:
        raise AssertionError(
            f"{expected_event_type} receipt event_type mismatch: {receipt.get('event_type')}"
        )

    if receipt.get("project_id") != project_id:
        raise AssertionError(
            f"{expected_event_type} receipt project_id mismatch: {receipt.get('project_id')} != {project_id}"
        )

    if receipt.get("assumption_id") != assumption_id:
        raise AssertionError(
            f"{expected_event_type} receipt assumption_id mismatch: {receipt.get('assumption_id')} != {assumption_id}"
        )

    return receipt_path


def run_probe() -> Dict[str, Any]:
    app = _build_isolated_app()
    client = TestClient(app)

    project_payload = _build_project_create_payload()
    project_response = _post_create_project(client, project_payload)

    project_id = project_response.get("project_id")
    if not project_id:
        raise AssertionError(f"Missing project_id in project create response: {project_response}")

    baseline_lock = project_response.get("baseline_lock", {})
    baseline_refs = baseline_lock.get("baseline_refs", {})
    if not baseline_refs:
        raise AssertionError("Project create response missing baseline_lock.baseline_refs")

    workflow_response = _post_initialize_workflow(
        client,
        project_id=project_id,
        phase_templates=_build_phase_templates(),
    )

    phase_instances = workflow_response.get("phase_instances", [])
    if not phase_instances:
        raise AssertionError("Workflow initialize response returned no phase_instances")

    first_phase = phase_instances[0]
    phase_id = first_phase.get("phase_id")
    if not phase_id:
        raise AssertionError(f"First phase instance missing phase_id: {first_phase}")

    change_packet_kwargs = _build_change_packet_kwargs(
        project_id=project_id,
        phase_id=phase_id,
        budget_baseline_id=baseline_refs["budget_baseline_id"],
        schedule_baseline_id=baseline_refs["schedule_baseline_id"],
        compliance_snapshot_id=baseline_refs["compliance_snapshot_id"],
    )
    change_response = _post_create_change_packet(client, change_packet_kwargs)

    change_packet = change_response.get("packet", {})
    linked_change_packet_id = change_packet.get("change_packet_id")
    if not linked_change_packet_id:
        raise AssertionError(f"Missing linked change packet id in change response: {change_response}")

    decision_entry_kwargs = _build_decision_entry_kwargs(
        project_id=project_id,
        phase_id=phase_id,
        linked_change_packet_id=linked_change_packet_id,
        compliance_snapshot_id=baseline_refs["compliance_snapshot_id"],
        schedule_baseline_id=baseline_refs["schedule_baseline_id"],
        budget_baseline_id=baseline_refs["budget_baseline_id"],
    )
    decision_response = _post_create_decision_entry(client, decision_entry_kwargs)

    decision_entry = decision_response.get("entry", {})
    linked_decision_id = decision_entry.get("decision_id")
    if not linked_decision_id:
        raise AssertionError(f"Missing linked decision id in decision response: {decision_response}")

    risk_entry_kwargs = _build_risk_entry_kwargs(
        project_id=project_id,
        linked_decision_id=linked_decision_id,
        linked_change_packet_id=linked_change_packet_id,
    )
    risk_response = _post_create_risk_entry(client, risk_entry_kwargs)

    risk_entry = risk_response.get("entry", {})
    linked_risk_id = risk_entry.get("risk_id")
    if not linked_risk_id:
        raise AssertionError(f"Missing linked risk id in risk response: {risk_response}")

    assumption_entry_kwargs = _build_assumption_entry_kwargs(
        project_id=project_id,
        linked_decision_id=linked_decision_id,
        linked_change_packet_id=linked_change_packet_id,
        linked_risk_id=linked_risk_id,
    )
    assumption_create_response = _post_create_assumption_entry(client, assumption_entry_kwargs)

    created_entry = assumption_create_response.get("entry", {})
    assumption_id = created_entry.get("assumption_id")
    if not assumption_id:
        raise AssertionError(f"Missing assumption_id in create response: {assumption_create_response}")

    assumption_transition_response = _post_transition_assumption_entry(client, created_entry)
    transitioned_entry = assumption_transition_response.get("entry", {})
    if transitioned_entry.get("assumption_id") != assumption_id:
        raise AssertionError("Transitioned assumption entry lost original assumption_id")

    assumption_invalidate_response = _post_invalidate_assumption_entry(
        client,
        transitioned_entry,
        linked_decision_id=linked_decision_id,
        linked_change_packet_id=linked_change_packet_id,
        linked_risk_id=linked_risk_id,
    )
    invalidated_entry = assumption_invalidate_response.get("entry", {})
    if invalidated_entry.get("assumption_id") != assumption_id:
        raise AssertionError("Invalidated assumption entry lost original assumption_id")

    conversion_record = assumption_invalidate_response.get("conversion_record", {})
    if conversion_record.get("conversion_option") != "Link_to_Risk":
        raise AssertionError(
            f"Expected conversion_option Link_to_Risk, got: {conversion_record.get('conversion_option')}"
        )

    assumptions_path = _verify_assumption_log(
        project_id=project_id,
        assumption_id=assumption_id,
        linked_decision_id=linked_decision_id,
        linked_change_packet_id=linked_change_packet_id,
        linked_risk_id=linked_risk_id,
    )

    create_receipt_path = _verify_assumption_receipt(
        receipt_path_str=assumption_create_response.get("receipt_path", ""),
        expected_event_type="create_assumption",
        project_id=project_id,
        assumption_id=assumption_id,
    )
    transition_receipt_path = _verify_assumption_receipt(
        receipt_path_str=assumption_transition_response.get("receipt_path", ""),
        expected_event_type="change_assumption_status",
        project_id=project_id,
        assumption_id=assumption_id,
    )
    invalidate_receipt_path = _verify_assumption_receipt(
        receipt_path_str=assumption_invalidate_response.get("receipt_path", ""),
        expected_event_type="invalidate_assumption",
        project_id=project_id,
        assumption_id=assumption_id,
    )

    summary = {
        "probe": "stage_contractor_assumption_probe",
        "mode": "isolated_router_only",
        "status": "passed",
        "project_id": project_id,
        "phase_id": phase_id,
        "linked_change_packet_id": linked_change_packet_id,
        "linked_decision_id": linked_decision_id,
        "linked_risk_id": linked_risk_id,
        "assumption_id": assumption_id,
        "verified_paths": {
            "assumption_log": str(assumptions_path),
            "create_assumption_receipt": str(create_receipt_path),
            "change_assumption_status_receipt": str(transition_receipt_path),
            "invalidate_assumption_receipt": str(invalidate_receipt_path),
        },
        "response_summary": {
            "create_status": assumption_create_response.get("status"),
            "transition_status": assumption_transition_response.get("status"),
            "invalidate_status": assumption_invalidate_response.get("status"),
            "final_validation_status": invalidated_entry.get("validation_status"),
            "conversion_option": conversion_record.get("conversion_option"),
            "project_name": project_payload["project_name"],
            "source_type": assumption_entry_kwargs["source_type"],
        },
    }
    return summary


def main() -> None:
    try:
        result = run_probe()
        print(json.dumps(result, indent=2, ensure_ascii=False))
        print("STAGE_CONTRACTOR_ASSUMPTION_PROBE: PASS")
    except Exception as exc:
        print(f"STAGE_CONTRACTOR_ASSUMPTION_PROBE: FAIL\n{exc}", file=sys.stderr)
        raise


if __name__ == "__main__":
    main()