from __future__ import annotations

"""
stage_contractor_router_probe.py

Purpose:
- Exercise the contractor_builder_v1 router API surface in isolation
- Verify that the router branch can:
  - create a real project
  - initialize workflow
  - persist lawful schedule blocks
  - detect schedule conflicts
  - build capacity posture
  - classify cascade risk
  - emit router receipts

Usage examples:
    python -m AI_GO.tests.stage_contractor_router_probe
    python AI_GO/tests/stage_contractor_router_probe.py

Notes:
- This is a probe, not a mocked unit test.
- It mounts only the contractor_builder_v1 router into a local FastAPI app.
- It uses a real project and real workflow phases, then overlays schedule blocks
  that intentionally create conflict and capacity pressure.
"""

import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Dict, List

from fastapi import FastAPI
from fastapi.testclient import TestClient


def _build_isolated_app() -> FastAPI:
    try:
        from AI_GO.api.contractor_builder_api import router as contractor_builder_router
    except Exception as exc:
        raise RuntimeError(
            "Unable to import isolated contractor builder router: "
            f"{exc}"
        ) from exc

    app = FastAPI(title="contractor_builder_v1_router_probe_app")
    app.include_router(contractor_builder_router)
    return app


def _now_compact() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")


def _build_project_create_payload() -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "project_name": f"Contractor Router Probe {unique}",
        "project_type": "Kitchen Remodel",
        "client_name": "Router Probe Client",
        "pm_name": "Router Probe PM",
        "jurisdiction": {
            "jurisdiction_id": "scottsburg-in",
            "authority_name": "Scottsburg Building Department",
            "city": "Scottsburg",
            "county": "Scott",
            "state": "IN",
        },
        "baseline_refs": {
            "schedule_baseline_id": f"schedule-baseline-{unique}",
            "budget_baseline_id": f"budget-baseline-{unique}",
            "compliance_snapshot_id": f"compliance-snapshot-{unique}",
        },
        "project_description": "Probe-created project for contractor router verification.",
        "client_contact": "router-probe-client@example.com",
        "pm_contact": "router-probe-pm@example.com",
        "site_address": "741 Router Lane, Scottsburg, IN",
        "portfolio_id": "portfolio-router-probe",
        "oracle_snapshot_id": "",
        "exposure_profile_id": "",
        "notes": "Generated by stage_contractor_router_probe.py",
    }


def _build_phase_templates() -> List[Dict[str, Any]]:
    return [
        {
            "template_id": "template-router-demolition",
            "project_type": "Kitchen Remodel",
            "phase_name": "Demolition",
            "expected_duration_days": 3,
            "dependencies": [],
            "role_expectations": {
                "crew": ["demo crew"],
                "management": ["pm oversight"],
            },
            "management_checkpoints": ["site protection verified"],
            "client_gate_requirement": {
                "required": False,
                "checklist": [],
            },
            "notes": "Initial demolition phase.",
        },
        {
            "template_id": "template-router-framing",
            "project_type": "Kitchen Remodel",
            "phase_name": "Framing",
            "expected_duration_days": 5,
            "dependencies": ["Demolition"],
            "role_expectations": {
                "crew": ["carpentry crew"],
                "management": ["pm walkthrough"],
            },
            "management_checkpoints": ["framing layout reviewed"],
            "client_gate_requirement": {
                "required": False,
                "checklist": [],
            },
            "notes": "Framing follows demolition.",
        },
    ]


def _post_create_project(client: TestClient, payload: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post("/contractor-builder/projects/create", json=payload)

    if response.status_code != 200:
        raise AssertionError(
            "Project create failed during router probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected project create status='created', got: {data}")

    return data


def _post_initialize_workflow(
    client: TestClient,
    project_id: str,
    phase_templates: List[Dict[str, Any]],
) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/workflow/initialize",
        json={
            "project_id": project_id,
            "phase_templates": phase_templates,
            "overwrite": False,
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Workflow initialize failed during router probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "initialized":
        raise AssertionError(f"Expected workflow status='initialized', got: {data}")

    return data


def _build_schedule_blocks(project_id: str, phase_instances: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    if len(phase_instances) < 2:
        raise AssertionError("Router probe requires at least 2 phase instances")

    phase_a = phase_instances[0]
    phase_b = phase_instances[1]

    phase_a_id = str(phase_a["phase_id"])
    phase_b_id = str(phase_b["phase_id"])

    return [
        {
            "block_id": f"block-{project_id}-demo-overlap",
            "project_id": project_id,
            "phase_id": phase_a_id,
            "block_type": "Crew_Assignment",
            "start_date": "2026-04-20",
            "end_date": "2026-04-22",
            "resource_name": "Shared Crew Alpha",
            "resource_type": "crew",
            "dependency_phase_ids": [],
            "notes": "Intentional overlap block for router probe.",
        },
        {
            "block_id": f"block-{project_id}-framing-overlap",
            "project_id": project_id,
            "phase_id": phase_b_id,
            "block_type": "Crew_Assignment",
            "start_date": "2026-04-21",
            "end_date": "2026-04-24",
            "resource_name": "Shared Crew Alpha",
            "resource_type": "crew",
            "dependency_phase_ids": [phase_a_id],
            "notes": "Intentional overlap + dependency pressure for router probe.",
        },
    ]


def _post_persist_blocks(
    client: TestClient,
    *,
    project_id: str,
    blocks: List[Dict[str, Any]],
) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/router/blocks",
        json={
            "project_id": project_id,
            "blocks": blocks,
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Router block persistence failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "stored":
        raise AssertionError(f"Expected router/blocks status='stored', got: {data}")

    return data


def _post_router_analyze(
    client: TestClient,
    *,
    project_id: str,
    blocks: List[Dict[str, Any]],
) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/router/analyze",
        json={
            "project_id": project_id,
            "blocks": blocks,
            "capacity_limits": {
                "Shared Crew Alpha": 1,
            },
            "report_id": f"router-report-{project_id}",
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Router analysis failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "ok":
        raise AssertionError(f"Expected router/analyze status='ok', got: {data}")

    return data


def _assert_file_exists(path_str: str, label: str) -> Path:
    path = Path(path_str)
    if not path.exists():
        raise AssertionError(f"Expected {label} to exist, but it was missing: {path}")
    return path


def _load_json(path: Path, label: str) -> Any:
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception as exc:
        raise AssertionError(f"Failed to load {label} JSON from {path}: {exc}") from exc


def _verify_blocks_persisted(
    *,
    project_id: str,
    blocks: List[Dict[str, Any]],
    blocks_response: Dict[str, Any],
) -> tuple[Path, Path]:
    blocks_path = _assert_file_exists(
        blocks_response.get("artifact_path", ""),
        "router schedule blocks artifact",
    )
    payload = _load_json(blocks_path, "router schedule blocks artifact")

    if payload.get("project_id") != project_id:
        raise AssertionError(
            f"schedule_blocks project_id mismatch: {payload.get('project_id')} != {project_id}"
        )

    if int(payload.get("block_count", -1)) != len(blocks):
        raise AssertionError(
            f"schedule_blocks block_count mismatch: {payload.get('block_count')} != {len(blocks)}"
        )

    persisted_blocks = payload.get("blocks", [])
    if len(persisted_blocks) != len(blocks):
        raise AssertionError(
            f"persisted blocks length mismatch: {len(persisted_blocks)} != {len(blocks)}"
        )

    receipt_path = _assert_file_exists(
        blocks_response.get("receipt_path", ""),
        "router store_schedule_blocks receipt",
    )
    receipt = _load_json(receipt_path, "router store_schedule_blocks receipt")

    if receipt.get("module_id") != "router":
        raise AssertionError(f"router receipt module_id mismatch: {receipt.get('module_id')}")

    if receipt.get("event_type") != "store_schedule_blocks":
        raise AssertionError(f"router receipt event_type mismatch: {receipt.get('event_type')}")

    if receipt.get("project_id") != project_id:
        raise AssertionError(
            f"router receipt project_id mismatch: {receipt.get('project_id')} != {project_id}"
        )

    return blocks_path, receipt_path


def _verify_router_analysis(
    *,
    project_id: str,
    analyze_response: Dict[str, Any],
) -> None:
    conflicts = analyze_response.get("conflicts", [])
    capacity_records = analyze_response.get("capacity_records", [])
    cascade = analyze_response.get("cascade_risk", {})
    receipt = analyze_response.get("receipt", {})

    if not conflicts:
        raise AssertionError("Expected at least one router conflict")

    conflict_types = {str(conflict.get("conflict_type", "")) for conflict in conflicts}
    if "Crew_Double_Booked" not in conflict_types:
        raise AssertionError(f"Expected Crew_Double_Booked conflict, got: {conflict_types}")

    if "Dependency_Violation" not in conflict_types:
        raise AssertionError(f"Expected Dependency_Violation conflict, got: {conflict_types}")

    if not capacity_records:
        raise AssertionError("Expected at least one capacity record")

    shared_crew_records = [
        record for record in capacity_records
        if record.get("resource_name") == "Shared Crew Alpha"
    ]
    if not shared_crew_records:
        raise AssertionError("Expected capacity record for Shared Crew Alpha")

    if shared_crew_records[0].get("capacity_status") != "Overloaded":
        raise AssertionError(
            f"Expected Shared Crew Alpha capacity_status Overloaded, got: {shared_crew_records[0].get('capacity_status')}"
        )

    if cascade.get("project_id") != project_id:
        raise AssertionError(
            f"cascade_risk project_id mismatch: {cascade.get('project_id')} != {project_id}"
        )

    if str(cascade.get("cascade_risk_label", "")).strip() not in {"moderate", "high"}:
        raise AssertionError(
            f"Expected cascade_risk_label moderate/high, got: {cascade.get('cascade_risk_label')}"
        )

    if int(cascade.get("conflict_count", 0)) < 2:
        raise AssertionError(
            f"Expected conflict_count >= 2, got: {cascade.get('conflict_count')}"
        )

    if receipt.get("module_id") != "router":
        raise AssertionError(f"analysis receipt module_id mismatch: {receipt.get('module_id')}")

    if receipt.get("event_type") != "run_conflict_scan":
        raise AssertionError(f"analysis receipt event_type mismatch: {receipt.get('event_type')}")

    if receipt.get("project_id") != project_id:
        raise AssertionError(
            f"analysis receipt project_id mismatch: {receipt.get('project_id')} != {project_id}"
        )


def run_probe() -> Dict[str, Any]:
    app = _build_isolated_app()
    client = TestClient(app)

    project_payload = _build_project_create_payload()
    project_response = _post_create_project(client, project_payload)

    project_id = project_response.get("project_id")
    if not project_id:
        raise AssertionError(f"Missing project_id in project create response: {project_response}")

    workflow_response = _post_initialize_workflow(
        client,
        project_id=project_id,
        phase_templates=_build_phase_templates(),
    )

    phase_instances = workflow_response.get("phase_instances", [])
    if len(phase_instances) < 2:
        raise AssertionError("Workflow initialize did not return enough phase instances for router probe")

    blocks = _build_schedule_blocks(project_id, phase_instances)

    blocks_response = _post_persist_blocks(
        client,
        project_id=project_id,
        blocks=blocks,
    )
    blocks_path, blocks_receipt_path = _verify_blocks_persisted(
        project_id=project_id,
        blocks=blocks,
        blocks_response=blocks_response,
    )

    analyze_response = _post_router_analyze(
        client,
        project_id=project_id,
        blocks=blocks,
    )
    _verify_router_analysis(
        project_id=project_id,
        analyze_response=analyze_response,
    )

    summary = {
        "probe": "stage_contractor_router_probe",
        "mode": "isolated_router_only",
        "status": "passed",
        "project_id": project_id,
        "verified_paths": {
            "schedule_blocks": str(blocks_path),
            "store_schedule_blocks_receipt": str(blocks_receipt_path),
        },
        "response_summary": {
            "blocks_status": blocks_response.get("status"),
            "analysis_status": analyze_response.get("status"),
            "project_name": project_payload["project_name"],
            "conflict_count": len(analyze_response.get("conflicts", [])),
            "capacity_record_count": len(analyze_response.get("capacity_records", [])),
            "cascade_risk_label": analyze_response.get("cascade_risk", {}).get("cascade_risk_label"),
        },
    }
    return summary


def main() -> None:
    try:
        result = run_probe()
        print(json.dumps(result, indent=2, ensure_ascii=False))
        print("STAGE_CONTRACTOR_ROUTER_PROBE: PASS")
    except Exception as exc:
        print(f"STAGE_CONTRACTOR_ROUTER_PROBE: FAIL\n{exc}", file=sys.stderr)
        raise


if __name__ == "__main__":
    main()