from __future__ import annotations

"""
stage_contractor_change_probe.py

Purpose:
- Exercise the contractor_builder_v1 change API surface in isolation
- Verify that the controlled-mutation branch can:
  - create a real project
  - initialize workflow
  - create a lawful change packet
  - append the change packet to change_packets.jsonl
  - emit the create_change_packet receipt

Usage examples:
    python -m AI_GO.tests.stage_contractor_change_probe
    python AI_GO/tests/stage_contractor_change_probe.py

Notes:
- This is a probe, not a mocked unit test.
- It mounts only the contractor_builder_v1 router into a local FastAPI app.
- It builds the minimum lawful context using a real project + real workflow phase.
"""

import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Dict, List, Tuple

from fastapi import FastAPI
from fastapi.testclient import TestClient


def _build_isolated_app() -> FastAPI:
    """
    Build a tiny isolated FastAPI app that mounts only the contractor router.
    """
    try:
        from AI_GO.api.contractor_builder_api import router as contractor_builder_router
    except Exception as exc:
        raise RuntimeError(
            "Unable to import isolated contractor builder router: "
            f"{exc}"
        ) from exc

    app = FastAPI(title="contractor_builder_v1_change_probe_app")
    app.include_router(contractor_builder_router)
    return app


def _now_compact() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")


def _build_project_create_payload() -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "project_name": f"Contractor Change Probe {unique}",
        "project_type": "Kitchen Remodel",
        "client_name": "Change Probe Client",
        "pm_name": "Change Probe PM",
        "jurisdiction": {
            "jurisdiction_id": "scottsburg-in",
            "authority_name": "Scottsburg Building Department",
            "city": "Scottsburg",
            "county": "Scott",
            "state": "IN",
        },
        "baseline_refs": {
            "schedule_baseline_id": f"schedule-baseline-{unique}",
            "budget_baseline_id": f"budget-baseline-{unique}",
            "compliance_snapshot_id": f"compliance-snapshot-{unique}",
        },
        "project_description": "Probe-created project for contractor change verification.",
        "client_contact": "change-probe-client@example.com",
        "pm_contact": "change-probe-pm@example.com",
        "site_address": "789 Change Lane, Scottsburg, IN",
        "portfolio_id": "portfolio-change-probe",
        "oracle_snapshot_id": "",
        "exposure_profile_id": "",
        "notes": "Generated by stage_contractor_change_probe.py",
    }


def _build_phase_templates() -> List[Dict[str, Any]]:
    return [
        {
            "template_id": "template-change-demolition",
            "project_type": "Kitchen Remodel",
            "phase_name": "Demolition",
            "expected_duration_days": 3,
            "dependencies": [],
            "role_expectations": {
                "crew": ["demo crew"],
                "management": ["pm oversight"],
            },
            "management_checkpoints": ["site protection verified"],
            "client_gate_requirement": {
                "required": False,
                "checklist": [],
            },
            "notes": "Initial demolition phase.",
        },
        {
            "template_id": "template-change-framing",
            "project_type": "Kitchen Remodel",
            "phase_name": "Framing",
            "expected_duration_days": 5,
            "dependencies": ["Demolition"],
            "role_expectations": {
                "crew": ["carpentry crew"],
                "management": ["pm walkthrough"],
            },
            "management_checkpoints": ["framing layout reviewed"],
            "client_gate_requirement": {
                "required": True,
                "checklist": ["layout approved"],
            },
            "notes": "Framing follows demolition.",
        },
    ]


def _post_create_project(client: TestClient, payload: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post("/contractor-builder/projects/create", json=payload)

    if response.status_code != 200:
        raise AssertionError(
            "Project create failed during change probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected project create status='created', got: {data}")

    return data


def _post_initialize_workflow(
    client: TestClient,
    project_id: str,
    phase_templates: List[Dict[str, Any]],
) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/workflow/initialize",
        json={
            "project_id": project_id,
            "phase_templates": phase_templates,
            "overwrite": False,
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Workflow initialize failed during change probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "initialized":
        raise AssertionError(f"Expected workflow status='initialized', got: {data}")

    return data


def _build_change_packet_kwargs(
    *,
    project_id: str,
    phase_id: str,
    budget_baseline_id: str,
    schedule_baseline_id: str,
    compliance_snapshot_id: str,
) -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "change_packet_id": f"change-packet-{unique}",
        "project_id": project_id,
        "phase_id": phase_id,
        "title": "Relocate outlet and adjust framing",
        "originator_name": "Change Probe PM",
        "originator_role": "Project Manager",
        "originator_org": "AI_GO Probe",
        "workflow_phase_state_snapshot_id": f"workflow-phase-snapshot-{unique}",
        "compliance_snapshot_id": compliance_snapshot_id,
        "drawing_revision_id": f"drawing-rev-{unique}",
        "budget_baseline_id": budget_baseline_id,
        "schedule_baseline_id": schedule_baseline_id,
        "scope_delta_description": "Add electrical relocation and framing adjustment.",
        "added_items": [
            "electrical relocation",
            "framing adjustment",
        ],
        "removed_items": [],
        "scope_notes": "Probe change packet for controlled mutation validation.",
        "phase_status": "not_started",
        "disruption_multiplier": 1.1,
        "factors_applied": ["demo_probe_context"],
    }


def _post_create_change_packet(client: TestClient, packet_kwargs: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/change/create",
        json={"packet_kwargs": packet_kwargs},
    )

    if response.status_code != 200:
        raise AssertionError(
            "Change packet create failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected change create status='created', got: {data}")

    return data


def _assert_file_exists(path_str: str, label: str) -> Path:
    path = Path(path_str)
    if not path.exists():
        raise AssertionError(f"Expected {label} to exist, but it was missing: {path}")
    return path


def _load_json(path: Path, label: str) -> Any:
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception as exc:
        raise AssertionError(f"Failed to load {label} JSON from {path}: {exc}") from exc


def _load_jsonl(path: Path, label: str) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    try:
        with path.open("r", encoding="utf-8") as handle:
            for line in handle:
                stripped = line.strip()
                if not stripped:
                    continue
                rows.append(json.loads(stripped))
    except Exception as exc:
        raise AssertionError(f"Failed to load {label} JSONL from {path}: {exc}") from exc
    return rows


def _verify_change_files(
    *,
    project_id: str,
    packet_kwargs: Dict[str, Any],
    change_response: Dict[str, Any],
) -> Path:
    project_root = Path("AI_GO/state/contractor_builder_v1/projects/by_project") / project_id
    change_packets_path = project_root / "change" / "change_packets.jsonl"

    _assert_file_exists(str(change_packets_path), "change packets log")

    rows = _load_jsonl(change_packets_path, "change packets log")
    if not rows:
        raise AssertionError("change_packets.jsonl exists but contains no records")

    latest = rows[-1]

    if latest.get("change_packet_id") != packet_kwargs["change_packet_id"]:
        raise AssertionError(
            "Latest change packet id mismatch: "
            f"{latest.get('change_packet_id')} != {packet_kwargs['change_packet_id']}"
        )

    if latest.get("project_id") != project_id:
        raise AssertionError(
            f"Latest change packet project_id mismatch: {latest.get('project_id')} != {project_id}"
        )

    if latest.get("phase_id") != packet_kwargs["phase_id"]:
        raise AssertionError(
            f"Latest change packet phase_id mismatch: {latest.get('phase_id')} != {packet_kwargs['phase_id']}"
        )

    if latest.get("title") != packet_kwargs["title"]:
        raise AssertionError(
            f"Latest change packet title mismatch: {latest.get('title')} != {packet_kwargs['title']}"
        )

    if latest.get("status") != "draft":
        raise AssertionError(
            f"Change packet should start as draft, got: {latest.get('status')}"
        )

    context_lock = latest.get("context_lock", {})
    for key in [
        "workflow_phase_state_snapshot_id",
        "compliance_snapshot_id",
        "drawing_revision_id",
        "budget_baseline_id",
        "schedule_baseline_id",
    ]:
        if context_lock.get(key) != packet_kwargs[key]:
            raise AssertionError(
                f"context_lock[{key}] mismatch: {context_lock.get(key)} != {packet_kwargs[key]}"
            )

    scope_delta = latest.get("scope_delta", {})
    if scope_delta.get("description") != packet_kwargs["scope_delta_description"]:
        raise AssertionError(
            "scope_delta.description mismatch: "
            f"{scope_delta.get('description')} != {packet_kwargs['scope_delta_description']}"
        )

    return change_packets_path


def _verify_change_receipt(
    *,
    project_id: str,
    packet_kwargs: Dict[str, Any],
    change_response: Dict[str, Any],
) -> Path:
    receipt_path = _assert_file_exists(
        change_response.get("receipt_path", ""),
        "change create receipt",
    )
    receipt = _load_json(receipt_path, "change receipt")

    if receipt.get("module_id") != "change":
        raise AssertionError(
            f"change receipt module_id mismatch: {receipt.get('module_id')}"
        )

    if receipt.get("event_type") != "create_change_packet":
        raise AssertionError(
            f"change receipt event_type mismatch: {receipt.get('event_type')}"
        )

    if receipt.get("project_id") != project_id:
        raise AssertionError(
            f"change receipt project_id mismatch: {receipt.get('project_id')} != {project_id}"
        )

    if receipt.get("change_packet_id") != packet_kwargs["change_packet_id"]:
        raise AssertionError(
            "change receipt change_packet_id mismatch: "
            f"{receipt.get('change_packet_id')} != {packet_kwargs['change_packet_id']}"
        )

    return receipt_path


def run_probe() -> Dict[str, Any]:
    app = _build_isolated_app()
    client = TestClient(app)

    project_payload = _build_project_create_payload()
    project_response = _post_create_project(client, project_payload)

    project_id = project_response.get("project_id")
    if not project_id:
        raise AssertionError(f"Missing project_id in project create response: {project_response}")

    baseline_lock = project_response.get("baseline_lock", {})
    baseline_refs = baseline_lock.get("baseline_refs", {})
    if not baseline_refs:
        raise AssertionError("Project create response missing baseline_lock.baseline_refs")

    phase_templates = _build_phase_templates()
    workflow_response = _post_initialize_workflow(client, project_id, phase_templates)

    phase_instances = workflow_response.get("phase_instances", [])
    if not phase_instances:
        raise AssertionError("Workflow initialize response returned no phase_instances")

    first_phase = phase_instances[0]
    phase_id = first_phase.get("phase_id")
    if not phase_id:
        raise AssertionError(f"First phase instance missing phase_id: {first_phase}")

    packet_kwargs = _build_change_packet_kwargs(
        project_id=project_id,
        phase_id=phase_id,
        budget_baseline_id=baseline_refs["budget_baseline_id"],
        schedule_baseline_id=baseline_refs["schedule_baseline_id"],
        compliance_snapshot_id=baseline_refs["compliance_snapshot_id"],
    )

    change_response = _post_create_change_packet(client, packet_kwargs)

    change_packets_path = _verify_change_files(
        project_id=project_id,
        packet_kwargs=packet_kwargs,
        change_response=change_response,
    )
    receipt_path = _verify_change_receipt(
        project_id=project_id,
        packet_kwargs=packet_kwargs,
        change_response=change_response,
    )

    summary = {
        "probe": "stage_contractor_change_probe",
        "mode": "isolated_router_only",
        "status": "passed",
        "project_id": project_id,
        "phase_id": phase_id,
        "change_packet_id": packet_kwargs["change_packet_id"],
        "verified_paths": {
            "change_packets": str(change_packets_path),
            "change_receipt": str(receipt_path),
        },
        "response_summary": {
            "status": change_response.get("status"),
            "project_name": project_payload["project_name"],
            "project_type": project_payload["project_type"],
            "change_title": packet_kwargs["title"],
        },
    }
    return summary


def main() -> None:
    try:
        result = run_probe()
        print(json.dumps(result, indent=2, ensure_ascii=False))
        print("STAGE_CONTRACTOR_CHANGE_PROBE: PASS")
    except Exception as exc:
        print(f"STAGE_CONTRACTOR_CHANGE_PROBE: FAIL\n{exc}", file=sys.stderr)
        raise


if __name__ == "__main__":
    main()