from __future__ import annotations

import json
import sys
from datetime import UTC, datetime
from typing import Any, Dict

from fastapi import FastAPI
from fastapi.testclient import TestClient


def _build_isolated_app() -> FastAPI:
    from AI_GO.api.contractor_builder_api import router as contractor_builder_router

    app = FastAPI(title="contractor_builder_v1_report_probe_app")
    app.include_router(contractor_builder_router)
    return app


def _now_compact() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")


def _post(client: TestClient, path: str, payload: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post(path, json=payload)
    if response.status_code != 200:
        raise AssertionError(
            f"{path} failed: {response.status_code} {response.text}"
        )
    return response.json()


def _assert_status(data: Dict[str, Any], expected: str, label: str) -> Dict[str, Any]:
    if data.get("status") != expected:
        raise AssertionError(f"{label} expected status={expected}, got: {data}")
    return data


def run_probe() -> Dict[str, Any]:
    app = _build_isolated_app()
    client = TestClient(app)

    uid = _now_compact()

    project = _assert_status(
        _post(
            client,
            "/contractor-builder/projects/create",
            {
                "project_name": f"Report Probe {uid}",
                "project_type": "Kitchen Remodel",
                "client_name": "Client",
                "pm_name": "PM",
                "jurisdiction": {
                    "jurisdiction_id": "scottsburg-in",
                    "authority_name": "Scottsburg Building Department",
                    "city": "Scottsburg",
                    "county": "Scott",
                    "state": "IN",
                },
                "baseline_refs": {
                    "schedule_baseline_id": f"s-{uid}",
                    "budget_baseline_id": f"b-{uid}",
                    "compliance_snapshot_id": f"c-{uid}",
                },
                "project_description": "Report probe project",
                "client_contact": "client@example.com",
                "pm_contact": "pm@example.com",
                "site_address": "123 Probe Street",
                "portfolio_id": "portfolio-report-probe",
                "oracle_snapshot_id": "snapshot-lumber-watch",
                "exposure_profile_id": f"e-{uid}",
                "notes": "Generated by stage_contractor_report_probe",
            },
        ),
        "created",
        "project_create",
    )

    project_id = project["project_id"]
    baseline_refs = project["baseline_lock"]["baseline_refs"]

    wf = _assert_status(
        _post(
            client,
            "/contractor-builder/workflow/initialize",
            {
                "project_id": project_id,
                "phase_templates": [
                    {
                        "template_id": "t1",
                        "project_type": "Kitchen Remodel",
                        "phase_name": "Demo",
                        "expected_duration_days": 3,
                        "dependencies": [],
                        "role_expectations": {
                            "crew": ["demo crew"],
                            "management": ["pm"],
                        },
                        "management_checkpoints": [],
                        "client_gate_requirement": {
                            "required": False,
                            "checklist": [],
                        },
                        "notes": "Demo phase",
                    }
                ],
                "overwrite": False,
            },
        ),
        "initialized",
        "workflow_initialize",
    )

    phase_id = wf["phase_instances"][0]["phase_id"]

    change = _assert_status(
        _post(
            client,
            "/contractor-builder/change/create",
            {
                "packet_kwargs": {
                    "change_packet_id": f"cp-{uid}",
                    "project_id": project_id,
                    "phase_id": phase_id,
                    "title": "Change",
                    "originator_name": "PM",
                    "originator_role": "PM",
                    "originator_org": "Org",
                    "workflow_phase_state_snapshot_id": f"workflow-snap-{uid}",
                    "compliance_snapshot_id": baseline_refs["compliance_snapshot_id"],
                    "drawing_revision_id": f"drawing-{uid}",
                    "budget_baseline_id": baseline_refs["budget_baseline_id"],
                    "schedule_baseline_id": baseline_refs["schedule_baseline_id"],
                    "scope_delta_description": "test",
                    "added_items": [],
                    "removed_items": [],
                    "scope_notes": "probe",
                    "phase_status": "not_started",
                    "disruption_multiplier": 1.0,
                    "factors_applied": [],
                }
            },
        ),
        "created",
        "change_create",
    )

    change_id = change["packet"]["change_packet_id"]

    decision = _assert_status(
        _post(
            client,
            "/contractor-builder/decision/create",
            {
                "entry_kwargs": {
                    "decision_id": f"d-{uid}",
                    "project_id": project_id,
                    "title": "Decision",
                    "decision_type": "Schedule_Adjustment",
                    "phase_id": phase_id,
                    "linked_change_packet_id": change_id,
                    "compliance_snapshot_id": baseline_refs["compliance_snapshot_id"],
                    "schedule_baseline_id": baseline_refs["schedule_baseline_id"],
                    "budget_baseline_id": baseline_refs["budget_baseline_id"],
                    "drawing_revision_id": f"drawing-{uid}",
                    "oracle_snapshot_id": "snapshot-lumber-watch",
                    "expected_schedule_delta_days": 1.0,
                    "expected_cost_delta_amount": 100.0,
                    "expected_margin_delta_percent": None,
                    "expected_risk_level": "Moderate",
                    "notes_on_assumptions": "probe",
                    "may_reference_in_owner_reports": True,
                    "owner_report_reference_label": "probe",
                    "notes_internal": "probe",
                    "attachments_refs": [],
                }
            },
        ),
        "created",
        "decision_create",
    )

    decision_id = decision["entry"]["decision_id"]

    risk = _assert_status(
        _post(
            client,
            "/contractor-builder/risk/create",
            {
                "entry_kwargs": {
                    "risk_id": f"r-{uid}",
                    "project_id": project_id,
                    "category": "Access_Logistics",
                    "description": "Risk",
                    "probability": "Moderate",
                    "impact_level": "Moderate",
                    "mitigation_strategy": "Plan",
                    "mitigation_owner": "PM",
                    "review_frequency": "weekly",
                    "linked_decision_ids": [decision_id],
                    "linked_change_packet_ids": [change_id],
                    "notes": "probe",
                }
            },
        ),
        "created",
        "risk_create",
    )

    risk_id = risk["entry"]["risk_id"]

    _assert_status(
        _post(
            client,
            "/contractor-builder/assumption/create",
            {
                "entry_kwargs": {
                    "assumption_id": f"a-{uid}",
                    "project_id": project_id,
                    "statement": "Test assumption",
                    "source_type": "Verbal",
                    "source_reference": "call",
                    "logged_by": "PM",
                    "owner_acknowledged": "Yes",
                    "validation_status": "Unverified",
                    "impact_if_false": "delay",
                    "linked_decision_ids": [decision_id],
                    "linked_change_packet_ids": [change_id],
                    "linked_risk_ids": [risk_id],
                    "notes": "probe",
                }
            },
        ),
        "created",
        "assumption_create",
    )

    comp = _assert_status(
        _post(
            client,
            "/contractor-builder/comply/snapshot",
            {
                "project_id": project_id,
                "jurisdiction": "IN",
            },
        ),
        "ok",
        "comply_snapshot",
    )

    router = _assert_status(
        _post(
            client,
            "/contractor-builder/router/analyze",
            {
                "project_id": project_id,
                "blocks": [],
                "capacity_limits": {},
                "report_id": f"router-report-{uid}",
            },
        ),
        "ok",
        "router_analyze",
    )

    oracle = _assert_status(
        _post(
            client,
            "/contractor-builder/oracle/project-external-pressure",
            {
                "project_id": project_id,
                "snapshot_id": "snapshot-lumber-watch",
                "exposure_profile_id": f"e-{uid}",
                "domain_exposure": {
                    "Lumber": "High",
                    "Steel": "Low",
                    "Fuel": "Moderate",
                },
            },
        ),
        "ok",
        "oracle",
    )

    report = _assert_status(
        _post(
            client,
            "/contractor-builder/report/project-weekly",
            {
                "project_id": project_id,
                "reporting_period_label": "2026-W16",
                "workflow_snapshot": wf["workflow_state"],
                "change_records": [change["packet"]],
                "compliance_snapshot": comp["snapshot"],
                "router_snapshot": {
                    "conflict_count": len(router.get("conflicts", [])),
                    "capacity_record_count": len(router.get("capacity_records", [])),
                    "cascade_risk": router.get("cascade_risk", {}),
                },
                "oracle_snapshot": {
                    "summary_label": oracle.get("risk_radar", {}).get("summary_label", ""),
                    "procurement_posture": oracle.get("procurement_advisory", {}).get(
                        "procurement_posture", ""
                    ),
                    "market_domain": oracle.get("snapshot", {}).get("market_domain", ""),
                    "shock_direction": oracle.get("shock", {}).get("shock_direction", ""),
                    "shock_severity": oracle.get("shock", {}).get("shock_severity", ""),
                },
                "decision_records": [decision["entry"]],
                "risk_records": [risk["entry"]],
                "assumption_records": [],
            },
        ),
        "ok",
        "project_report",
    )

    if report["report"]["report_status"] != "pm_review":
        raise AssertionError("Report not in pm_review")

    return {
        "status": "passed",
        "project_id": project_id,
        "report_id": report["report"]["report_id"],
    }


def main() -> None:
    try:
        result = run_probe()
        print(json.dumps(result, indent=2))
        print("STAGE_CONTRACTOR_REPORT_PROBE: PASS")
    except Exception as exc:
        print("STAGE_CONTRACTOR_REPORT_PROBE: FAIL")
        print(exc)
        raise


if __name__ == "__main__":
    main()