from __future__ import annotations

"""
stage_contractor_comply_probe.py

Purpose:
- Exercise the contractor_builder_v1 compliance API surface in isolation
- Verify that the comply branch can:
  - create a real project
  - generate required permits for a jurisdiction
  - generate required inspections for a jurisdiction
  - build a compliance snapshot
  - compute blocking logic correctly
  - run a bounded code lookup

Usage examples:
    python -m AI_GO.tests.stage_contractor_comply_probe
    python AI_GO/tests/stage_contractor_comply_probe.py

Notes:
- This is a probe, not a mocked unit test.
- It mounts only the contractor_builder_v1 router into a local FastAPI app.
- The current comply API returns the compliance receipt inline rather than writing
  a receipt file path, so this probe verifies the returned receipt payload directly.
"""

import json
import sys
from datetime import UTC, datetime
from typing import Any, Dict, List

from fastapi import FastAPI
from fastapi.testclient import TestClient


def _build_isolated_app() -> FastAPI:
    try:
        from AI_GO.api.contractor_builder_api import router as contractor_builder_router
    except Exception as exc:
        raise RuntimeError(
            "Unable to import isolated contractor builder router: "
            f"{exc}"
        ) from exc

    app = FastAPI(title="contractor_builder_v1_comply_probe_app")
    app.include_router(contractor_builder_router)
    return app


def _now_compact() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")


def _build_project_create_payload() -> Dict[str, Any]:
    unique = _now_compact()

    return {
        "project_name": f"Contractor Comply Probe {unique}",
        "project_type": "Kitchen Remodel",
        "client_name": "Comply Probe Client",
        "pm_name": "Comply Probe PM",
        "jurisdiction": {
            "jurisdiction_id": "scottsburg-in",
            "authority_name": "Scottsburg Building Department",
            "city": "Scottsburg",
            "county": "Scott",
            "state": "IN",
        },
        "baseline_refs": {
            "schedule_baseline_id": f"schedule-baseline-{unique}",
            "budget_baseline_id": f"budget-baseline-{unique}",
            "compliance_snapshot_id": f"compliance-snapshot-{unique}",
        },
        "project_description": "Probe-created project for contractor compliance verification.",
        "client_contact": "comply-probe-client@example.com",
        "pm_contact": "comply-probe-pm@example.com",
        "site_address": "852 Compliance Lane, Scottsburg, IN",
        "portfolio_id": "portfolio-comply-probe",
        "oracle_snapshot_id": "",
        "exposure_profile_id": "",
        "notes": "Generated by stage_contractor_comply_probe.py",
    }


def _post_create_project(client: TestClient, payload: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post("/contractor-builder/projects/create", json=payload)

    if response.status_code != 200:
        raise AssertionError(
            "Project create failed during comply probe.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "created":
        raise AssertionError(f"Expected project create status='created', got: {data}")

    return data


def _post_required_compliance(
    client: TestClient,
    *,
    project_id: str,
    jurisdiction: str,
) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/comply/required",
        json={
            "project_id": project_id,
            "jurisdiction": jurisdiction,
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Compliance required-generation failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "ok":
        raise AssertionError(f"Expected comply/required status='ok', got: {data}")

    return data


def _post_compliance_snapshot(
    client: TestClient,
    *,
    project_id: str,
    jurisdiction: str,
    permits: List[Dict[str, Any]],
    inspections: List[Dict[str, Any]],
) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/comply/snapshot",
        json={
            "project_id": project_id,
            "jurisdiction": jurisdiction,
            "permits": permits,
            "inspections": inspections,
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Compliance snapshot build failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "ok":
        raise AssertionError(f"Expected comply/snapshot status='ok', got: {data}")

    return data


def _post_code_lookup(
    client: TestClient,
    *,
    jurisdiction: str,
    category: str,
) -> Dict[str, Any]:
    response = client.post(
        "/contractor-builder/comply/code-lookup",
        json={
            "jurisdiction": jurisdiction,
            "category": category,
        },
    )

    if response.status_code != 200:
        raise AssertionError(
            "Compliance code lookup failed.\n"
            f"status_code={response.status_code}\n"
            f"response_text={response.text}"
        )

    data = response.json()
    if data.get("status") != "ok":
        raise AssertionError(f"Expected comply/code-lookup status='ok', got: {data}")

    return data


def _verify_required_outputs(
    *,
    project_id: str,
    jurisdiction: str,
    required_response: Dict[str, Any],
) -> None:
    permits = required_response.get("permits", [])
    inspections = required_response.get("inspections", [])

    if not isinstance(permits, list) or not permits:
        raise AssertionError("Expected non-empty permits list")

    if not isinstance(inspections, list) or not inspections:
        raise AssertionError("Expected non-empty inspections list")

    for permit in permits:
        if permit.get("record_type") != "permit":
            raise AssertionError(f"Permit record_type mismatch: {permit}")
        if permit.get("project_id") != project_id:
            raise AssertionError(f"Permit project_id mismatch: {permit}")
        if permit.get("jurisdiction") != jurisdiction:
            raise AssertionError(f"Permit jurisdiction mismatch: {permit}")
        if permit.get("required") is not True:
            raise AssertionError(f"Permit required flag mismatch: {permit}")
        if permit.get("status") != "pending":
            raise AssertionError(f"Permit status should start pending: {permit}")
        if permit.get("blocking") is not True:
            raise AssertionError(f"Permit blocking flag should start true: {permit}")

    for inspection in inspections:
        if inspection.get("record_type") != "inspection":
            raise AssertionError(f"Inspection record_type mismatch: {inspection}")
        if inspection.get("project_id") != project_id:
            raise AssertionError(f"Inspection project_id mismatch: {inspection}")
        if inspection.get("status") != "pending":
            raise AssertionError(f"Inspection status should start pending: {inspection}")
        if inspection.get("passed") is not False:
            raise AssertionError(f"Inspection passed flag should start false: {inspection}")
        if inspection.get("blocking") is not True:
            raise AssertionError(f"Inspection blocking flag should start true: {inspection}")


def _verify_snapshot_response(
    *,
    project_id: str,
    snapshot_response: Dict[str, Any],
    expected_permit_count: int,
    expected_inspection_count: int,
) -> None:
    snapshot = snapshot_response.get("snapshot", {})
    receipt = snapshot_response.get("receipt", {})

    if snapshot.get("record_type") != "compliance_snapshot":
        raise AssertionError(f"Snapshot record_type mismatch: {snapshot}")

    if snapshot.get("project_id") != project_id:
        raise AssertionError(
            f"Snapshot project_id mismatch: {snapshot.get('project_id')} != {project_id}"
        )

    if int(snapshot.get("blocking_count", -1)) <= 0:
        raise AssertionError(f"Expected blocking_count > 0, got: {snapshot.get('blocking_count')}")

    if snapshot.get("blocking") is not True:
        raise AssertionError("Expected initial compliance snapshot to be blocking")

    permits = snapshot.get("permits", [])
    inspections = snapshot.get("inspections", [])

    if len(permits) != expected_permit_count:
        raise AssertionError(
            f"Snapshot permit count mismatch: {len(permits)} != {expected_permit_count}"
        )

    if len(inspections) != expected_inspection_count:
        raise AssertionError(
            f"Snapshot inspection count mismatch: {len(inspections)} != {expected_inspection_count}"
        )

    if receipt.get("receipt_type") != "compliance_layer":
        raise AssertionError(f"Compliance receipt type mismatch: {receipt}")

    if receipt.get("project_id") != project_id:
        raise AssertionError(
            f"Compliance receipt project_id mismatch: {receipt.get('project_id')} != {project_id}"
        )

    if receipt.get("blocking") is not True:
        raise AssertionError("Compliance receipt should show blocking=True")

    summary = receipt.get("summary", {})
    if int(summary.get("permits", -1)) != expected_permit_count:
        raise AssertionError(
            f"Compliance receipt permit summary mismatch: {summary.get('permits')} != {expected_permit_count}"
        )

    if int(summary.get("inspections", -1)) != expected_inspection_count:
        raise AssertionError(
            f"Compliance receipt inspection summary mismatch: {summary.get('inspections')} != {expected_inspection_count}"
        )


def _verify_code_lookup_response(
    *,
    code_lookup_response: Dict[str, Any],
    jurisdiction: str,
    category: str,
) -> None:
    result = code_lookup_response.get("result", {})

    if result.get("record_type") != "code_lookup":
        raise AssertionError(f"Code lookup record_type mismatch: {result}")

    if result.get("jurisdiction") != jurisdiction:
        raise AssertionError(
            f"Code lookup jurisdiction mismatch: {result.get('jurisdiction')} != {jurisdiction}"
        )

    if result.get("code_category") != category:
        raise AssertionError(
            f"Code lookup category mismatch: {result.get('code_category')} != {category}"
        )

    requirements = result.get("requirements", [])
    if not isinstance(requirements, list) or not requirements:
        raise AssertionError("Expected non-empty code lookup requirements list")


def run_probe() -> Dict[str, Any]:
    app = _build_isolated_app()
    client = TestClient(app)

    project_payload = _build_project_create_payload()
    project_response = _post_create_project(client, project_payload)

    project_id = project_response.get("project_id")
    if not project_id:
        raise AssertionError(f"Missing project_id in project create response: {project_response}")

    # Use the deterministic state code from the working project payload.
    jurisdiction = project_payload["jurisdiction"]["state"]

    required_response = _post_required_compliance(
        client,
        project_id=project_id,
        jurisdiction=jurisdiction,
    )
    _verify_required_outputs(
        project_id=project_id,
        jurisdiction=jurisdiction,
        required_response=required_response,
    )

    permits = required_response["permits"]
    inspections = required_response["inspections"]

    snapshot_response = _post_compliance_snapshot(
        client,
        project_id=project_id,
        jurisdiction=jurisdiction,
        permits=permits,
        inspections=inspections,
    )
    _verify_snapshot_response(
        project_id=project_id,
        snapshot_response=snapshot_response,
        expected_permit_count=len(permits),
        expected_inspection_count=len(inspections),
    )

    code_lookup_response = _post_code_lookup(
        client,
        jurisdiction=jurisdiction,
        category="electrical",
    )
    _verify_code_lookup_response(
        code_lookup_response=code_lookup_response,
        jurisdiction=jurisdiction,
        category="electrical",
    )

    summary = {
        "probe": "stage_contractor_comply_probe",
        "mode": "isolated_router_only",
        "status": "passed",
        "project_id": project_id,
        "verified_counts": {
            "permit_count": len(permits),
            "inspection_count": len(inspections),
            "blocking_count": snapshot_response["snapshot"]["blocking_count"],
        },
        "response_summary": {
            "required_status": required_response.get("status"),
            "snapshot_status": snapshot_response.get("status"),
            "code_lookup_status": code_lookup_response.get("status"),
            "project_name": project_payload["project_name"],
            "jurisdiction": jurisdiction,
            "blocking": snapshot_response["snapshot"]["blocking"],
            "code_lookup_category": "electrical",
        },
    }
    return summary


def main() -> None:
    try:
        result = run_probe()
        print(json.dumps(result, indent=2, ensure_ascii=False))
        print("STAGE_CONTRACTOR_COMPLY_PROBE: PASS")
    except Exception as exc:
        print(f"STAGE_CONTRACTOR_COMPLY_PROBE: FAIL\n{exc}", file=sys.stderr)
        raise


if __name__ == "__main__":
    main()