from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List


PROBE_NAME = "STAGE_E2E_CONTRACTOR_VALIDATION_PROBE"


def _stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _record_result(
    results: List[Dict[str, Any]],
    *,
    step: str,
    passed: bool,
    detail: Dict[str, Any] | None = None,
) -> None:
    results.append(
        {
            "step": step,
            "passed": bool(passed),
            "detail": detail or {},
        }
    )


def _safe_list(value: Any) -> List[Any]:
    return value if isinstance(value, list) else []


def _safe_dict(value: Any) -> Dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _safe_str(value: Any) -> str:
    return str(value or "").strip()


def _status_in(payload: Dict[str, Any], allowed: set[str]) -> bool:
    return _safe_str(payload.get("status")).lower() in allowed


def _first_phase_id(phase_instances: List[Dict[str, Any]]) -> str:
    for item in phase_instances:
        if isinstance(item, dict):
            phase_id = _safe_str(item.get("phase_id"))
            if phase_id:
                return phase_id
    return ""


def _canonical_phase_instances_from_initialize(
    workflow_result: Dict[str, Any],
) -> List[Dict[str, Any]]:
    actual = workflow_result.get("phase_instances")
    if isinstance(actual, list) and actual:
        return [dict(item) for item in actual if isinstance(item, dict)]

    candidate = workflow_result.get("candidate_phase_instances")
    if isinstance(candidate, list) and candidate:
        return [dict(item) for item in candidate if isinstance(item, dict)]

    return []


def _canonical_phase_id(
    *,
    workflow_result: Dict[str, Any],
    phase_instances: List[Dict[str, Any]],
) -> str:
    workflow_state = _safe_dict(workflow_result.get("workflow_state"))
    current_phase_id = _safe_str(workflow_state.get("current_phase_id"))
    if current_phase_id:
        return current_phase_id

    current_phase_id = _safe_str(workflow_result.get("current_phase_id"))
    if current_phase_id:
        return current_phase_id

    phase_id = _safe_str(workflow_result.get("phase_id"))
    if phase_id:
        return phase_id

    return _first_phase_id(phase_instances)


def _phase_instances_with_status(
    *,
    phase_instances: List[Dict[str, Any]],
    phase_id: str,
    phase_status: str,
) -> List[Dict[str, Any]]:
    updated: List[Dict[str, Any]] = []
    clean_phase_id = _safe_str(phase_id)

    for phase in phase_instances:
        if not isinstance(phase, dict):
            continue

        phase_record = dict(phase)

        if _safe_str(phase_record.get("phase_id")) == clean_phase_id:
            phase_record["phase_status"] = phase_status

            gate = phase_record.get("client_gate_requirement")
            if isinstance(gate, dict):
                gate_record = dict(gate)
                gate_record["status"] = "approved"
                phase_record["client_gate_requirement"] = gate_record

        updated.append(phase_record)

    return updated


def _build_ready_contractor_flow(results: List[Dict[str, Any]]) -> Dict[str, Any]:
    from AI_GO.child_cores.contractor_builder_v1.ui.project_intake_runner import (
        create_project_from_form,
    )
    from AI_GO.child_cores.contractor_builder_v1.workflow.workflow_service import (
        initialize_workflow,
        repair_upsert_workflow,
        upsert_workflow_checklist,
        update_workflow_signoff_status,
    )
    from AI_GO.child_cores.contractor_builder_v1.decision_log.decision_service import (
        create_decision,
    )
    from AI_GO.child_cores.contractor_builder_v1.risk_register.risk_service import (
        create_risk,
    )
    from AI_GO.child_cores.contractor_builder_v1.assumption_log.assumption_service import (
        create_assumption,
    )

    stamp = _stamp()

    project_result = create_project_from_form(
        {
            "project_name": f"Northstar Validation Probe {stamp}",
            "project_type": "Residential Renovation",
            "project_description": "Northstar contractor validation certification probe.",
            "client_name": "Northstar Client",
            "client_email": "client@example.com",
            "pm_name": "Northstar PM",
            "pm_email": "pm@example.com",
            "site_address": "100 Probe Street",
            "portfolio_id": "portfolio-northstar-e2e",
            "city": "Louisville",
            "county": "Jefferson",
            "state": "KY",
            "authority_name": "Northstar Test Authority",
            "notes": f"Generated by {PROBE_NAME}.",
        }
    )

    project_profile = dict(project_result.get("project_profile", {}))
    baseline_lock = dict(project_result.get("baseline_lock", {}))
    project_id = _safe_str(project_profile.get("project_id"))

    _record_result(
        results,
        step="project_created",
        passed=bool(project_id and project_profile and baseline_lock),
        detail={
            "project_id": project_id,
            "has_project_profile": bool(project_profile),
            "has_baseline_lock": bool(baseline_lock),
            "receipt_paths": project_result.get("receipt_paths", {}),
        },
    )

    workflow_result = initialize_workflow(
        {
            "project_id": project_id,
            "overwrite": True,
            "actor": PROBE_NAME,
            "phase_templates": [
                {
                    "template_id": "template-northstar-validation-closeout",
                    "project_type": "Residential Renovation",
                    "phase_name": "Validation Certification Phase",
                    "expected_duration_days": 1,
                    "dependencies": [],
                    "role_expectations": {
                        "crew": ["probe crew"],
                        "management": ["probe pm"],
                    },
                    "management_checkpoints": [
                        "checklist completed",
                        "signoff posture verified",
                    ],
                    "client_gate_requirement": {
                        "required": True,
                        "checklist": ["item-1", "item-2"],
                        "status": "pending",
                    },
                    "notes": f"Generated by {PROBE_NAME}.",
                }
            ],
        }
    )

    phase_instances = _canonical_phase_instances_from_initialize(workflow_result)
    phase_id = _canonical_phase_id(
        workflow_result=workflow_result,
        phase_instances=phase_instances,
    )

    _record_result(
        results,
        step="workflow_initialized",
        passed=bool(
            workflow_result.get("mode") == "governed_execution"
            and workflow_result.get("status") == "initialized"
            and phase_instances
            and phase_id
        ),
        detail={
            "project_id": project_id,
            "phase_id": phase_id,
            "phase_count": len(phase_instances),
            "mode": workflow_result.get("mode"),
            "status": workflow_result.get("status"),
            "receipt_path": workflow_result.get("receipt_path"),
        },
    )

    if not phase_instances:
        raise ValueError("initialize_workflow returned no phase instances")
    if not phase_id:
        raise ValueError("phase_id could not be derived from canonical workflow state")

    commit_result = repair_upsert_workflow(
        {
            "project_id": project_id,
            "phase_instances": phase_instances,
            "actor": PROBE_NAME,
            "reconcile_after_write": True,
        }
    )

    committed_phase_instances = _safe_list(commit_result.get("phase_instances"))
    if committed_phase_instances:
        phase_instances = [
            dict(item)
            for item in committed_phase_instances
            if isinstance(item, dict)
        ]

    commit_phase_id = _safe_str(
        _safe_dict(commit_result.get("workflow_state")).get("current_phase_id")
    ) or _safe_str(commit_result.get("current_phase_id"))

    if commit_phase_id:
        phase_id = commit_phase_id

    _record_result(
        results,
        step="workflow_committed",
        passed=bool(
            commit_result.get("mode") == "governed_execution"
            and _status_in(
                commit_result,
                {"repaired", "updated", "ok", "persisted", "completed"},
            )
            and phase_id
        ),
        detail={
            "project_id": project_id,
            "phase_id": phase_id,
            "mode": commit_result.get("mode"),
            "status": commit_result.get("status"),
            "receipt_path": commit_result.get("receipt_path"),
            "artifact_path": commit_result.get("artifact_path"),
            "phase_count": len(phase_instances),
        },
    )

    checklist_result = upsert_workflow_checklist(
        {
            "project_id": project_id,
            "phase_id": phase_id,
            "actor": PROBE_NAME,
            "items": [
                {
                    "item_id": "item-1",
                    "phase_id": phase_id,
                    "label": "Confirm prerequisite one",
                    "required": True,
                    "status": "complete",
                    "completed_by": PROBE_NAME,
                    "notes": "Probe checklist item complete.",
                },
                {
                    "item_id": "item-2",
                    "phase_id": phase_id,
                    "label": "Confirm prerequisite two",
                    "required": True,
                    "status": "complete",
                    "completed_by": PROBE_NAME,
                    "notes": "Probe checklist item complete.",
                },
            ],
        }
    )

    checklist_summary = _safe_dict(checklist_result.get("checklist_summary"))

    _record_result(
        results,
        step="checklist_upserted",
        passed=bool(
            checklist_result.get("mode") == "governed_execution"
            and _status_in(
                checklist_result,
                {"updated", "ok", "persisted", "completed"},
            )
            and checklist_summary.get("ready_for_signoff") is True
        ),
        detail={
            "mode": checklist_result.get("mode"),
            "status": checklist_result.get("status"),
            "receipt_path": checklist_result.get("receipt_path"),
            "artifact_path": checklist_result.get("artifact_path"),
            "checklist_summary": checklist_summary,
        },
    )

    signoff_result = update_workflow_signoff_status(
        {
            "project_id": project_id,
            "phase_id": phase_id,
            "client_name": "Northstar Client",
            "client_email": "client@example.com",
            "signoff_action": "signed",
            "artifact_id": f"artifact-validation-{stamp}",
            "actor": PROBE_NAME,
        }
    )

    _record_result(
        results,
        step="signoff_status_signed",
        passed=bool(
            signoff_result.get("mode") == "governed_execution"
            and _status_in(
                signoff_result,
                {"updated", "ok", "recorded", "persisted", "completed"},
            )
        ),
        detail={
            "mode": signoff_result.get("mode"),
            "status": signoff_result.get("status"),
            "receipt_path": signoff_result.get("receipt_path"),
            "artifact_path": signoff_result.get("artifact_path"),
        },
    )

    signoff_ready_instances = _phase_instances_with_status(
        phase_instances=phase_instances,
        phase_id=phase_id,
        phase_status="awaiting_signoff",
    )

    signoff_posture_result = repair_upsert_workflow(
        {
            "project_id": project_id,
            "phase_instances": signoff_ready_instances,
            "actor": PROBE_NAME,
            "reconcile_after_write": True,
        }
    )

    updated_instances = _safe_list(signoff_posture_result.get("phase_instances"))
    if updated_instances:
        phase_instances = [
            dict(item)
            for item in updated_instances
            if isinstance(item, dict)
        ]

    canonical_phase_id = _safe_str(
        _safe_dict(signoff_posture_result.get("workflow_state")).get(
            "current_phase_id"
        )
    ) or _safe_str(signoff_posture_result.get("current_phase_id"))

    if canonical_phase_id:
        phase_id = canonical_phase_id

    _record_result(
        results,
        step="phase_moved_to_awaiting_signoff",
        passed=bool(
            signoff_posture_result.get("mode") == "governed_execution"
            and _status_in(
                signoff_posture_result,
                {"repaired", "updated", "ok", "persisted", "completed"},
            )
        ),
        detail={
            "mode": signoff_posture_result.get("mode"),
            "status": signoff_posture_result.get("status"),
            "phase_id": phase_id,
            "receipt_path": signoff_posture_result.get("receipt_path"),
            "artifact_path": signoff_posture_result.get("artifact_path"),
        },
    )

    decision_result = create_decision(
        {
            "actor": PROBE_NAME,
            "entry_kwargs": {
                "project_id": project_id,
                "decision_title": "Northstar Validation Decision",
                "decision_summary": "Verify decision creation inside validation flow.",
                "decision_type": "Scope",
                "requested_by": "Northstar Probe",
                "requester_role": "Tester",
                "requester_org": "AI_GO",
                "approver_name": "Northstar PM",
                "approver_role": "PM",
                "approver_org": "AI_GO",
                "decision_reason": "Validation certification",
                "impact_summary": "No production impact.",
            },
        }
    )

    decision_entry = dict(decision_result.get("entry", {}))
    decision_id = _safe_str(decision_entry.get("decision_id"))

    _record_result(
        results,
        step="decision_created",
        passed=bool(
            decision_result.get("mode") == "governed_execution"
            and decision_result.get("status") == "created"
            and decision_id
            and decision_result.get("receipt_path")
        ),
        detail={
            "decision_id": decision_id,
            "mode": decision_result.get("mode"),
            "status": decision_result.get("status"),
            "receipt_path": decision_result.get("receipt_path"),
            "artifact_path": decision_result.get("artifact_path"),
        },
    )

    risk_result = create_risk(
        {
            "actor": PROBE_NAME,
            "entry_kwargs": {
                "project_id": project_id,
                "risk_id": f"risk-validation-{stamp}",
                "category": "Other",
                "description": "Northstar validation risk record.",
                "probability": "Moderate",
                "impact_level": "Moderate",
                "mitigation_strategy": "Monitor probe output and governance receipts.",
                "mitigation_owner": "Northstar PM",
                "review_frequency": "weekly",
                "status": "Open",
                "linked_decision_ids": [decision_id] if decision_id else [],
                "linked_change_packet_ids": [],
                "notes": f"Generated by {PROBE_NAME}.",
            },
        }
    )

    risk_entry = dict(risk_result.get("entry", {}))
    risk_id = _safe_str(risk_entry.get("risk_id"))

    _record_result(
        results,
        step="risk_created",
        passed=bool(
            risk_result.get("mode") == "governed_execution"
            and risk_result.get("status") == "created"
            and risk_id
            and risk_result.get("receipt_path")
        ),
        detail={
            "risk_id": risk_id,
            "mode": risk_result.get("mode"),
            "status": risk_result.get("status"),
            "receipt_path": risk_result.get("receipt_path"),
            "artifact_path": risk_result.get("artifact_path"),
        },
    )

    assumption_result = create_assumption(
        {
            "actor": PROBE_NAME,
            "entry_kwargs": {
                "project_id": project_id,
                "assumption_id": f"assumption-validation-{stamp}",
                "statement": "Northstar validation assumption record.",
                "source_type": "Other",
                "source_reference": PROBE_NAME,
                "logged_by": PROBE_NAME,
                "impact_if_false": "Validation flow needs repair.",
                "linked_decision_ids": [decision_id] if decision_id else [],
                "linked_risk_ids": [risk_id] if risk_id else [],
                "linked_change_packet_ids": [],
                "notes": f"Generated by {PROBE_NAME}.",
            },
        }
    )

    assumption_entry = dict(assumption_result.get("entry", {}))
    assumption_id = _safe_str(assumption_entry.get("assumption_id"))

    _record_result(
        results,
        step="assumption_created",
        passed=bool(
            assumption_result.get("mode") == "governed_execution"
            and assumption_result.get("status") == "created"
            and assumption_id
            and assumption_result.get("receipt_path")
        ),
        detail={
            "assumption_id": assumption_id,
            "mode": assumption_result.get("mode"),
            "status": assumption_result.get("status"),
            "receipt_path": assumption_result.get("receipt_path"),
            "artifact_path": assumption_result.get("artifact_path"),
        },
    )

    return {
        "stamp": stamp,
        "project_id": project_id,
        "phase_id": phase_id,
        "project_profile": project_profile,
        "baseline_lock": baseline_lock,
        "phase_instances": phase_instances,
        "decision_entry": decision_entry,
        "risk_entry": risk_entry,
        "assumption_entry": assumption_entry,
    }


def run_probe() -> Dict[str, Any]:
    from AI_GO.child_cores.contractor_builder_v1.phase_closeout.phase_closeout_service import (
        check_phase_closeout,
    )
    from AI_GO.child_cores.contractor_builder_v1.ui.contractor_dashboard_runner import (
        run_contractor_dashboard,
    )

    results: List[Dict[str, Any]] = []
    project_id = ""
    phase_id = ""

    try:
        flow = _build_ready_contractor_flow(results)
        project_id = flow["project_id"]
        phase_id = flow["phase_id"]
        project_profile = flow["project_profile"]
        baseline_lock = flow["baseline_lock"]
        stamp = flow["stamp"]

        closeout_check = check_phase_closeout(
            {
                "project_id": project_id,
                "phase_id": phase_id,
                "client_email": "client@example.com",
                "client_name": "Northstar Client",
                "project_name": project_profile.get("project_name", ""),
                "actor": PROBE_NAME,
                "allow_resend_if_sent": True,
                "operator_approved": False,
            }
        )

        state_valid = closeout_check.get("state", {}).get("valid") is True
        watcher_valid = closeout_check.get("watcher", {}).get("valid") is True
        governance_allowed = (
            closeout_check.get("governance_decision", {}).get("allowed") is True
        )

        _record_result(
            results,
            step="phase_closeout_validation_passed_execution_blocked",
            passed=bool(state_valid and watcher_valid and not governance_allowed),
            detail={
                "state_valid": state_valid,
                "watcher_valid": watcher_valid,
                "governance_allowed": governance_allowed,
                "expected_governance_block": True,
                "project_id": closeout_check.get("project_id"),
                "phase_id": closeout_check.get("phase_id"),
            },
        )

        dashboard_result = run_contractor_dashboard(
            request_id=f"request-validation-{stamp}",
            project_profile=project_profile,
            baseline_lock=baseline_lock,
            workflow_snapshot={
                "project_id": project_id,
                "current_phase_id": phase_id,
                "workflow_status": "active",
                "phase_status": "awaiting_signoff",
            },
            latest_project_report={
                "report_id": f"report-validation-{stamp}",
                "project_id": project_id,
                "reporting_period_label": "Northstar Validation",
                "summary": "Synthetic report payload for dashboard assembly.",
                "status": "generated",
                "risk_count": 1,
                "decision_count": 1,
                "assumption_count": 1,
            },
            portfolio_report=None,
            decision_records=[flow["decision_entry"]],
            change_records=[],
            compliance_snapshot={},
            risk_records=[flow["risk_entry"]],
            phase_signoff_status="signed",
            checklist_summary={
                "ready_for_signoff": True,
                "required_item_count": 2,
                "completed_required_count": 2,
                "phase_id": phase_id,
            },
            checklist_items=[
                {
                    "item_id": "item-1",
                    "phase_id": phase_id,
                    "required": True,
                    "status": "complete",
                },
                {
                    "item_id": "item-2",
                    "phase_id": phase_id,
                    "required": True,
                    "status": "complete",
                },
            ],
        )

        _record_result(
            results,
            step="dashboard_built",
            passed=bool(isinstance(dashboard_result, dict) and dashboard_result),
            detail={
                "dashboard_keys": sorted(dashboard_result.keys())
                if isinstance(dashboard_result, dict)
                else [],
            },
        )

    except Exception as exc:
        _record_result(
            results,
            step="probe_exception",
            passed=False,
            detail={
                "error_type": type(exc).__name__,
                "error": str(exc),
                "project_id": project_id,
                "phase_id": phase_id,
            },
        )

    failed = [item for item in results if item.get("passed") is not True]

    return {
        "probe": PROBE_NAME,
        "status": "passed" if not failed else "failed",
        "failed_count": len(failed),
        "failed": failed,
        "results": results,
        "project_id": project_id,
        "phase_id": phase_id,
        "certification_type": "validation_only",
        "state_expected": "passed",
        "watcher_expected": "passed",
        "governance_expected": "blocked",
        "mutation_allowed": True,
        "writes_performed": True,
        "external_delivery_performed": False,
        "phase_closeout_run_performed": False,
    }


if __name__ == "__main__":
    output = run_probe()
    print(f"{PROBE_NAME}: {output['status'].upper()}")
    print("\nOUTPUT:\n", output)
