from __future__ import annotations

import json
import sys
from datetime import UTC, datetime
from typing import Any, Dict

from fastapi import FastAPI
from fastapi.testclient import TestClient


def _build_isolated_app() -> FastAPI:
    from AI_GO.api.contractor_builder_api import router as contractor_builder_router

    app = FastAPI(title="contractor_weekly_cycle_probe_app")
    app.include_router(contractor_builder_router)
    return app


def _now_compact() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")


def _post(client: TestClient, path: str, payload: Dict[str, Any]) -> Dict[str, Any]:
    response = client.post(path, json=payload)
    if response.status_code != 200:
        raise AssertionError(
            f"{path} failed: {response.status_code} {response.text}"
        )
    return response.json()


def _assert_status(data: Dict[str, Any], expected: str, label: str) -> Dict[str, Any]:
    if data.get("status") != expected:
        raise AssertionError(f"{label} expected status={expected}, got: {data}")
    return data


def _build_project_payload(
    *,
    project_id: str,
    portfolio_id: str,
    reporting_period_label: str,
) -> Dict[str, Any]:
    return {
        "project_id": project_id,
        "portfolio_id": portfolio_id,
        "reporting_period_label": reporting_period_label,
        "workflow_snapshot": {
            "project_id": project_id,
            "workflow_status": "initialized",
            "phase_count": 1,
            "current_phase_id": "",
        },
        "change_records": [],
        "compliance_snapshot": {
            "project_id": project_id,
            "blocking": False,
            "blocking_count": 0,
            "permits": [],
            "inspections": [],
        },
        "router_snapshot": {
            "conflict_count": 0,
            "capacity_record_count": 0,
            "cascade_risk": {
                "cascade_risk_label": "none",
                "conflict_count": 0,
                "dependency_violation_count": 0,
                "overloaded_resource_count": 0,
            },
        },
        "oracle_snapshot": {
            "summary_label": "stable_external_pressure",
            "procurement_posture": "Watch",
            "market_domain": "Lumber",
            "shock_direction": "flat",
            "shock_severity": "none",
        },
        "decision_records": [],
        "risk_records": [],
        "assumption_records": [],
    }


def run_probe() -> Dict[str, Any]:
    app = _build_isolated_app()
    client = TestClient(app)

    uid = _now_compact()
    reporting_period_label = "2026-W16"
    portfolio_id = "portfolio-weekly-cycle-probe"

    project = _assert_status(
        _post(
            client,
            "/contractor-builder/projects/create",
            {
                "project_name": f"Weekly Cycle Probe {uid}",
                "project_type": "Kitchen Remodel",
                "client_name": "Client",
                "pm_name": "PM",
                "jurisdiction": {
                    "jurisdiction_id": "scottsburg-in",
                    "authority_name": "Scottsburg Building Department",
                    "city": "Scottsburg",
                    "county": "Scott",
                    "state": "IN",
                },
                "baseline_refs": {
                    "schedule_baseline_id": f"s-{uid}",
                    "budget_baseline_id": f"b-{uid}",
                    "compliance_snapshot_id": f"c-{uid}",
                },
                "project_description": "Weekly cycle probe project",
                "client_contact": "client@example.com",
                "pm_contact": "pm@example.com",
                "site_address": "123 Probe Street",
                "portfolio_id": portfolio_id,
                "oracle_snapshot_id": "snapshot-lumber-watch",
                "exposure_profile_id": f"e-{uid}",
                "notes": "Generated by stage_contractor_weekly_cycle_probe",
            },
        ),
        "created",
        "project_create",
    )

    project_id = project["project_id"]

    project_payload = _build_project_payload(
        project_id=project_id,
        portfolio_id=portfolio_id,
        reporting_period_label=reporting_period_label,
    )

    cycle = _post(
        client,
        "/contractor-builder/weekly-cycle/run",
        {
            "reporting_period_label": reporting_period_label,
            "project_payloads": [project_payload],
            "portfolio_project_map": {
                portfolio_id: [project_id],
            },
        },
    )

    if cycle.get("status") != "completed":
        raise AssertionError(
            f"weekly_cycle expected status=completed, got: {cycle}"
        )

    cycle_record = cycle.get("cycle_record", {})
    if not cycle_record.get("cycle_id"):
        raise AssertionError("Missing cycle_id in cycle_record")

    if cycle_record.get("project_report_count") != 1:
        raise AssertionError(
            f"Expected project_report_count=1, got: {cycle_record.get('project_report_count')}"
        )

    if cycle_record.get("portfolio_report_count") != 1:
        raise AssertionError(
            f"Expected portfolio_report_count=1, got: {cycle_record.get('portfolio_report_count')}"
        )

    if cycle_record.get("errors"):
        raise AssertionError(f"Expected no cycle errors, got: {cycle_record.get('errors')}")

    return {
        "status": "passed",
        "cycle_id": cycle_record["cycle_id"],
        "project_id": project_id,
        "portfolio_id": portfolio_id,
        "project_report_count": cycle_record.get("project_report_count"),
        "portfolio_report_count": cycle_record.get("portfolio_report_count"),
        "receipt_path": cycle.get("receipt_path"),
    }


def main() -> None:
    try:
        result = run_probe()
        print(json.dumps(result, indent=2))
        print("STAGE_CONTRACTOR_WEEKLY_CYCLE_PROBE: PASS")
    except Exception as exc:
        print("STAGE_CONTRACTOR_WEEKLY_CYCLE_PROBE: FAIL")
        print(exc)
        raise


if __name__ == "__main__":
    main()