REQUIRED_ESCALATION_DECISION_FIELDS = {
    "escalation_decision_id",
    "escalation_decision_type",
    "timestamp",
    "summary",
    "result",
    "source_receipt_ref",
    "source_receipt_type",
    "payload_class",
    "route_class",
    "execution_mode",
    "source_adapter_class",
    "retry_adapter_class",
    "escalation_required",
    "escalation_class",
    "escalation_route",
}

REQUIRED_ESCALATION_EXECUTION_RESULT_FIELDS = {
    "escalation_execution_id",
    "escalation_execution_result_type",
    "timestamp",
    "summary",
    "result",
    "escalation_decision_ref",
    "source_receipt_ref",
    "source_receipt_type",
    "payload_class",
    "route_class",
    "execution_mode",
    "source_adapter_class",
    "retry_adapter_class",
    "escalation_class",
    "escalation_route",
    "escalation_adapter_class",
    "escalation_attempted",
    "escalation_permitted",
}

INTERNAL_FIELD_NAMES = {
    "_internal_state",
    "_debug_trace",
    "_raw_payload",
    "_authority_override",
    "_transport_secret",
    "_adapter_state",
    "_receipt_private_state",
    "_retry_private_state",
    "_retry_executor_secret",
    "_retry_outcome_secret",
    "_escalation_secret",
    "_escalation_executor_secret",
}