from __future__ import annotations

REGISTRY = {
    "accepted_artifact_type": "external_memory_promotion",
    "accepted_receipt_type": "external_memory_promotion_receipt",
    "emitted_artifact_type": "external_memory_pattern_aggregation",
    "emitted_receipt_type": "external_memory_pattern_aggregation_receipt",
    "emitted_rejection_receipt_type": "external_memory_pattern_aggregation_rejection_receipt",
    "allowed_requester_profiles": {"operator", "analyzer", "pm"},
    "allowed_target_cores": {"market_analyzer_v1"},
    "required_promotion_artifact_fields": {
        "artifact_type",
        "target_core",
        "requester_profile",
        "promotion_status",
        "promoted_records",
        "promoted_record_count",
        "provenance_refs",
    },
    "required_promotion_receipt_fields": {
        "receipt_type",
        "artifact_type",
        "target_core",
        "requester_profile",
        "status",
    },
    "required_promoted_record_fields": {
        "memory_id",
        "symbol",
        "sector",
        "event_theme",
        "source_quality",
        "trust_class",
        "adjusted_weight",
        "observed_at",
    },
    "pattern_strengths": (
        "weak_pattern",
        "forming_pattern",
        "strong_pattern",
        "dominant_pattern",
    ),
    "pattern_postures": (
        "light_pattern_context",
        "useful_pattern_context",
        "strong_pattern_context",
    ),
    "historical_confirmations": (
        "low_confirmation",
        "moderate_confirmation",
        "high_confirmation",
    ),
    "failure_reasons": {
        "invalid_promotion_artifact_type",
        "invalid_promotion_receipt_type",
        "artifact_receipt_misalignment",
        "target_not_allowed",
        "requester_profile_not_allowed",
        "promotion_status_not_promoted",
        "empty_promoted_records",
        "missing_required_fields",
        "invalid_record_shape",
    },
}